# Boomer → Gen Alpha Clean Dataset Generator — Local VS Code Version

This notebook is configured for local execution in VS Code.

Expected folder:

```text
/Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation/
├── input/
│   └── BoomerAlpha50K.csv
├── output/
├── partials/
├── logs/
└── .env
```

Put your Gemini API key in `.env`:

```env
GEMINI_API_KEY=your_api_key_here
```

Run on CPU. No GPU is required because generation uses the Gemini API.

In [1]:
# =============================================================================
# 2. IMPORTS + LOCAL PROJECT SETUP
# =============================================================================
from pathlib import Path
import os
import json
import time
import random

import pandas as pd
import numpy as np
from tqdm import tqdm
from dotenv import load_dotenv

# Local project folder
PROJECT_DIR = Path("/Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation")
INPUT_DIR = PROJECT_DIR / "input"
OUTPUT_DIR = PROJECT_DIR / "output"
PARTIAL_DIR = PROJECT_DIR / "partials"
LOG_DIR = PROJECT_DIR / "logs"

for d in [INPUT_DIR, OUTPUT_DIR, PARTIAL_DIR, LOG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

SOURCE_CSV = INPUT_DIR / "BoomerAlpha50K.csv"

# Output paths for this 25K generation run
STRATIFIED_SOURCE_CSV = OUTPUT_DIR / "source_25000_stratified.csv"
FINAL_OUTPUT_CSV = OUTPUT_DIR / "generated_25000_gemini25_flashlite_prompt_final.csv"
PARTIAL_GENERATED_CSV = PARTIAL_DIR / "generated_25000_partial_prompt_final.csv"
ERROR_LOG = LOG_DIR / "generated_25000_errors_prompt_final.txt"
FAILED_BATCHES_CSV = LOG_DIR / "failed_generation_batches_25000_prompt_final.csv"

print("Project folder:", PROJECT_DIR)
print("Source exists:", SOURCE_CSV.exists())
print("Source path:", SOURCE_CSV)

if not SOURCE_CSV.exists():
    raise FileNotFoundError(f"Dataset not found at {SOURCE_CSV}. Put BoomerAlpha50K.csv inside the input folder.")

Project folder: /Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation
Source exists: True
Source path: /Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation/input/BoomerAlpha50K.csv

In [2]:
# =============================================================================
# 3. GEMINI API SETUP FROM .env
# =============================================================================
from google import genai

# Load .env from project folder
load_dotenv(PROJECT_DIR / ".env")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if GEMINI_API_KEY is None or not GEMINI_API_KEY.strip():
    raise ValueError(
        "GEMINI_API_KEY not found. Create a .env file in the project folder with: GEMINI_API_KEY=your_api_key_here"
    )

client = genai.Client(api_key=GEMINI_API_KEY)

# If this model is unavailable in your account, change it to the exact name from Google AI Studio.
GEMINI_MODEL = "gemini-2.5-flash-lite"

print("Gemini client ready.")
print("Model:", GEMINI_MODEL)

Gemini client ready.
Model: gemini-2.5-flash-lite

In [3]:
# =============================================================================
# 4. LOAD DATASET + CLEAN SOURCE DATA
# =============================================================================
df = pd.read_csv(SOURCE_CSV)

print("Original dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

if "boomer" not in df.columns:
    raise ValueError("Dataset must contain a 'boomer' column.")

metadata_cols = ["topic", "boomer_style", "gen_alpha_style", "sentence_type"]

for col in metadata_cols:
    if col not in df.columns:
        print(f"Missing metadata column {col!r}, filling with 'unknown'.")
        df[col] = "unknown"

# Keep only needed source-side columns
src_all = df[["boomer", "topic", "boomer_style", "gen_alpha_style", "sentence_type"]].copy()

# Basic cleaning
for col in src_all.columns:
    src_all[col] = src_all[col].fillna("unknown").astype(str).str.strip()
    src_all.loc[src_all[col] == "", col] = "unknown"

src_all = src_all[src_all["boomer"] != "unknown"].copy()

# Remove duplicate source rows
src_all = src_all.drop_duplicates(
    subset=["boomer", "topic", "boomer_style", "gen_alpha_style", "sentence_type"]
).reset_index(drop=True)

print("Clean source dataset shape:", src_all.shape)
display(src_all.head())

Original dataset shape: (49910, 6)
Columns: ['boomer', 'gen_alpha', 'topic', 'boomer_style', 'gen_alpha_style', 'sentence_type']
Clean source dataset shape: (49910, 5)

,boomer,topic,boomer_style,gen_alpha_style,sentence_type
0,"You should really get some more fresh air, it'...",health and medicine,unsolicited advice-giver,delulu and delusional optimism,exclamations or reactions
1,Make sure to take your vitamins every day.,health and medicine,unsolicited advice-giver,delulu and delusional optimism,exclamations or reactions
2,You need to eat more vegetables for better hea...,health and medicine,unsolicited advice-giver,delulu and delusional optimism,exclamations or reactions
3,Don't forget to hydrate throughout the day.,health and medicine,unsolicited advice-giver,delulu and delusional optimism,exclamations or reactions
4,You should really get your annual check-up.,health and medicine,unsolicited advice-giver,delulu and delusional optimism,exclamations or reactions

In [4]:
# =============================================================================
# 5. STRATIFIED SAMPLING SOURCE ROWS TO 25,000
# =============================================================================
TARGET_N = 25000
SEED = 42

# Stratify mainly by topic + sentence_type
src_all = src_all.copy()
src_all["strata"] = (
    src_all["topic"].astype(str) + " | " + src_all["sentence_type"].astype(str)
)

if len(src_all) <= TARGET_N:
    src_df = src_all.copy()
else:
    sampled_parts = []
    strata_counts = src_all["strata"].value_counts()
    total = len(src_all)

    for strata, count in strata_counts.items():
        group = src_all[src_all["strata"] == strata]

        # Proportional allocation
        n_sample = round((count / total) * TARGET_N)

        # Ensure at least 1 row from every stratum
        n_sample = max(1, n_sample)

        # Do not sample more than available
        n_sample = min(n_sample, len(group))

        sampled_parts.append(group.sample(n=n_sample, random_state=SEED))

    src_df = pd.concat(sampled_parts).drop_duplicates().reset_index(drop=True)

    # Adjust if over target
    if len(src_df) > TARGET_N:
        src_df = src_df.sample(n=TARGET_N, random_state=SEED).reset_index(drop=True)

    # Adjust if under target
    elif len(src_df) < TARGET_N:
        # More robust remaining selection using merge indicator
        base_cols = ["boomer", "topic", "boomer_style", "gen_alpha_style", "sentence_type"]
        current_keys = src_df[base_cols].copy()
        remaining = src_all.drop(columns=["strata"], errors="ignore").merge(
            current_keys,
            on=base_cols,
            how="left",
            indicator=True,
        )
        remaining = remaining[remaining["_merge"] == "left_only"].drop(columns=["_merge"])

        needed = TARGET_N - len(src_df)
        if len(remaining) >= needed:
            extra = remaining.sample(n=needed, random_state=SEED)
            src_df = pd.concat([src_df.drop(columns=["strata"], errors="ignore"), extra]).reset_index(drop=True)

# Remove helper stratum column
src_df = src_df.drop(columns=["strata"], errors="ignore").reset_index(drop=True)

# Assign stable row_id from 0 to N-1
src_df = src_df.reset_index().rename(columns={"index": "row_id"})

# Save stratified source rows
src_df.to_csv(STRATIFIED_SOURCE_CSV, index=False)

print("Final source rows to generate:", len(src_df))
print("Saved stratified source to:", STRATIFIED_SOURCE_CSV)

print("\nTopic coverage:", src_df["topic"].nunique())
print("Sentence type coverage:", src_df["sentence_type"].nunique())
print("Boomer style coverage:", src_df["boomer_style"].nunique())
print("Gen Alpha style coverage:", src_df["gen_alpha_style"].nunique())

print("\nTopic distribution:")
display(src_df["topic"].value_counts())

print("\nSentence type distribution:")
display(src_df["sentence_type"].value_counts())

print("\nTopic + sentence_type distribution:")
display(
    src_df.groupby(["topic", "sentence_type"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
    .head(30)
)

Final source rows to generate: 25000
Saved stratified source to: /Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation/output/source_25000_stratified.csv

Topic coverage: 15
Sentence type coverage: 8
Boomer style coverage: 12
Gen Alpha style coverage: 12

Topic distribution:

topic
gaming and hobbies               2094
money and work                   1858
health and medicine              1810
weather and environment          1799
technology and social media      1758
family and home                  1755
food and cooking                 1724
relationships and dating         1644
politics and news                1591
fashion and style                1552
travel and going out             1531
school and studying              1481
pop culture and entertainment    1468
sports and fitness               1468
mental health and feelings       1467
Name: count, dtype: int64

Sentence type distribution:

sentence_type
compliments or praise         3504
complaints or frustrations    3246
requests or suggestions       3240
warnings or advice            3180
questions                     3119
commands or instructions      3016
exclamations or reactions     2849
observations or statements    2846
Name: count, dtype: int64

Topic + sentence_type distribution:

                             topic               sentence_type  count
30              gaming and hobbies     requests or suggestions    389
31              gaming and hobbies          warnings or advice    373
53                  money and work                   questions    372
103    technology and social media          warnings or advice    363
34             health and medicine       compliments or praise    358
24              gaming and hobbies    commands or instructions    348
118        weather and environment     requests or suggestions    325
74        relationships and dating       compliments or praise    322
37             health and medicine                   questions    320
58               politics and news       compliments or praise    317
73        relationships and dating  complaints or frustrations    314
2                  family and home       compliments or praise    314
1                  family and home  complaints or frustrations    305
50                  money and work       compliments or praise    300
99     technology and social media   exclamations or reactions    297
16                food and cooking    commands or instructions    295
66   pop culture and entertainment       compliments or praise    290
77        relationships and dating                   questions    286
96     technology and social media    commands or instructions    285
87             school and studying          warnings or advice    285
115        weather and environment   exclamations or reactions    280
45      mental health and feelings                   questions    278
22                food and cooking     requests or suggestions    276
36             health and medicine  observations or statements    274
10               fashion and style       compliments or praise    268
20                food and cooking  observations or statements    267
113        weather and environment  complaints or frustrations    263
82             school and studying       compliments or praise    257
105           travel and going out  complaints or frustrations    249
49                  money and work  complaints or frustrations    248

In [5]:
# =============================================================================
# 6. FINAL REVISED PROMPT FUNCTION
# =============================================================================
def build_generation_prompt(batch_df):
    rows = []

    for _, row in batch_df.iterrows():
        rows.append({
            "row_id": int(row["row_id"]),
            "topic": str(row["topic"]),
            "boomer_style": str(row["boomer_style"]),
            "target_gen_alpha_style": str(row["gen_alpha_style"]),
            "sentence_type": str(row["sentence_type"]),
            "boomer": str(row["boomer"]),
        })

    prompt = f"""
You are creating a high-quality NLP dataset for Boomer-to-Gen Alpha STYLE TRANSLATION.

Task:
Rewrite each Boomer-style sentence into Gen Alpha-style language.

This is NOT a dialogue-response task.
The target sentence must NOT reply to, argue with, defend against, mock, reject, or contradict the source sentence.
The target sentence must preserve the original meaning, intention, and speech act.

Core objective:
Boomer-style sentence -> same meaning in Gen Alpha-style sentence

Critical rules:
1. Preserve the exact same meaning.
2. Preserve the same intention.
3. Preserve the same speech act.
4. If the source is a command, the target must remain a command.
5. If the source is advice, the target must remain advice.
6. If the source is a warning, the target must remain a warning.
7. If the source is praise, the target must remain praise.
8. If the source is encouragement, the target must remain encouragement.
9. Do not create an excuse, emotional reaction, comeback, or defensive response.
10. Only change the style, not the message.
11. Keep the output school-appropriate.
12. The target should sound natural, not forced or cringe.
13. Return one output for every input row. Do not skip any row.

Style rules:
1. Use clearly informal Gen Alpha / internet-native phrasing, but prioritize meaning preservation over slang intensity.
2. Do not overuse slang.
3. Avoid repeating the same slang too often.
4. Do not use \"vibe\", \"no cap\", \"main character\", \"legendary\", \"low-key\", \"like\", \"slay\", or \"fam\" too often.
5. Use varied phrasing across rows.
6. Prefer clear, casual, internet-native wording over random slang.
7. Avoid awkward metaphors.
8. The output should sound like something a real young person might actually say.
9. Mild slang is better than forced slang if stronger slang would change the meaning.
10. Do not make the sentence too dramatic unless the source is already dramatic.

Scoring rules:
- Use score 5 only when the target preserves the meaning and speech act almost perfectly.
- Use score 4 when the target mostly preserves meaning but has a small metaphorical shift, simplification, or tone adjustment.
- Do not assign 5 to every row.
- If a row is difficult, still produce the best meaning-preserving style translation and assign score 4.
- If the target becomes a reply, contradiction, excuse, or emotional reaction, rewrite it until it becomes a valid style translation.
- Only output semantic_preservation_score 4 or 5.

Bad examples:

Source: Stop playing games and clean your room.
Wrong target: Cleaning is for NPCs, I am the main character.
Reason: This contradicts the command.

Source: You should stop staying up late every night.
Wrong target: Late nights are when the magic happens, trust.
Reason: This gives the opposite advice.

Source: Spending too much money is irresponsible.
Wrong target: I buy what I want because life is short.
Reason: This is a defensive reply, not a translation.

Source: Put your phone down when someone is talking.
Wrong target: My phone understands me better than people.
Reason: This is an emotional response, not a translation.

Good examples:

Source: Stop playing games and clean your room.
Correct target: Pause the game rn and clean your room, side quest time.
Score: 5
Reason: The command is preserved and rewritten with casual internet style.

Source: You should stop staying up late every night.
Correct target: Staying up late every night is not the move, go get some sleep.
Score: 5
Reason: The advice is preserved and rewritten naturally.

Source: Spending too much money is irresponsible.
Correct target: Blowing all your money on random stuff is not it.
Score: 5
Reason: The warning is preserved without becoming defensive.

Source: Reading could help improve your mental well-being.
Correct target: Reading can be a solid brain reset when life feels heavy.
Score: 4
Reason: The advice is mostly preserved, but the wording slightly shifts the mental well-being idea into a metaphor.

Source: Proper posture is important for your back.
Correct target: Good posture helps your back stay unbothered.
Score: 5
Reason: The health advice is preserved with casual phrasing.

Source: You always volunteer to help at home.
Correct target: You always help out at home, and that is actually so clutch.
Score: 5
Reason: The praise is preserved using natural informal wording.

Source: You should be careful about which medicines you take.
Correct target: Be careful with the meds you take, do not just wing it.
Score: 5
Reason: The warning is preserved clearly with casual phrasing.

Return JSON only.
Return a list of objects with this exact schema:
[
  {{
    \"row_id\": 0,
    \"gen_alpha\": \"rewritten sentence\",
    \"semantic_preservation_score\": 5,
    \"notes\": \"short explanation\"
  }}
]

Important output requirements:
- Return valid JSON only.
- Return a JSON list, not a dictionary.
- Include every row_id from the input rows exactly once.
- Do not include markdown fences.
- Do not add extra commentary outside the JSON.

Rows:
{json.dumps(rows, ensure_ascii=False)}
"""
    return prompt

In [6]:
# =============================================================================
# 7. ROBUST JSON PARSING
# =============================================================================
def parse_json_response(text):
    if text is None:
        raise ValueError("Response text is None.")

    text = text.strip()

    # Remove markdown code fences if present
    if text.startswith("```"):
        parts = text.split("```")
        if len(parts) >= 2:
            text = parts[1].strip()
            if text.startswith("json"):
                text = text[4:].strip()

    # Direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Extract JSON list
    start = text.find("[")
    end = text.rfind("]")

    if start != -1 and end != -1 and end > start:
        extracted = text[start:end + 1]
        return json.loads(extracted)

    raise ValueError("Could not parse JSON response.")

In [7]:
# =============================================================================
# 8. GENERATION SETTINGS + ROBUST GENERATE FUNCTION
# =============================================================================
BATCH_SIZE = 10
SLEEP_SECONDS = 3
MAX_RETRIES = 8
BASE_SLEEP_SECONDS = 5

def generate_batch(batch_df):
    prompt = build_generation_prompt(batch_df)

    expected_ids = set(batch_df["row_id"].astype(int).tolist())

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
            )

            text = response.text
            parsed = parse_json_response(text)

            if not isinstance(parsed, list):
                raise ValueError("Parsed response is not a list.")

            cleaned = []
            returned_ids = set()

            for item in parsed:
                if not isinstance(item, dict):
                    continue

                if "row_id" not in item:
                    continue

                row_id = int(item["row_id"])

                if row_id not in expected_ids:
                    continue

                gen_alpha = str(item.get("gen_alpha", "")).strip()
                score = item.get("semantic_preservation_score", 4)
                notes = str(item.get("notes", "")).strip()

                try:
                    score = int(float(score))
                except Exception:
                    score = 4

                # Clamp score to 4 or 5 only
                if score < 4:
                    score = 4
                if score > 5:
                    score = 5

                if not gen_alpha:
                    continue

                cleaned.append({
                    "row_id": row_id,
                    "gen_alpha": gen_alpha,
                    "semantic_preservation_score": score,
                    "notes": notes,
                })

                returned_ids.add(row_id)

            missing_ids = expected_ids - returned_ids
            if missing_ids:
                raise ValueError(f"Missing row_id(s) in response: {sorted(missing_ids)}")

            return cleaned

        except Exception as e:
            print(f"\nGeneration attempt {attempt}/{MAX_RETRIES} failed.")
            print("Error:", repr(e))

            with open(ERROR_LOG, "a", encoding="utf-8") as f:
                f.write(f"\nAttempt {attempt}/{MAX_RETRIES} failed.\n")
                f.write(f"Batch row_ids: {batch_df['row_id'].astype(int).tolist()}\n")
                f.write(f"Error: {repr(e)}\n")

            # Exponential backoff + jitter
            sleep_time = BASE_SLEEP_SECONDS * (2 ** (attempt - 1))
            sleep_time = min(sleep_time, 120)
            sleep_time += random.uniform(0, 3)

            print(f"Waiting {sleep_time:.1f} seconds before retrying...")
            time.sleep(sleep_time)

    return None

In [11]:
# =============================================================================
# 9. RUN GENERATION WITH AUTOSAVE + RESUME
# =============================================================================
generated_rows = []

# Resume existing partial if available
if PARTIAL_GENERATED_CSV.exists():
    partial_df = pd.read_csv(PARTIAL_GENERATED_CSV)

    if not partial_df.empty and "row_id" in partial_df.columns:
        partial_df["row_id"] = partial_df["row_id"].astype(int)
        partial_df = partial_df.drop_duplicates(subset=["row_id"], keep="last")
        generated_rows = partial_df.to_dict("records")
        done_ids = set(partial_df["row_id"].astype(int).tolist())
        print("Resuming from partial. Already generated:", len(done_ids))
    else:
        done_ids = set()
        print("Partial exists but invalid/empty. Starting fresh.")
else:
    done_ids = set()
    print("Starting fresh.")

pending_df = src_df[~src_df["row_id"].isin(done_ids)].copy()

print("Total target rows:", len(src_df))
print("Already done:", len(done_ids))
print("Pending rows:", len(pending_df))

failed_batches = []

# Load existing failed batches if available
if FAILED_BATCHES_CSV.exists():
    try:
        old_failed = pd.read_csv(FAILED_BATCHES_CSV)
        failed_batches = old_failed.to_dict("records")
    except Exception:
        failed_batches = []

for start in tqdm(range(0, len(pending_df), BATCH_SIZE)):
    batch_df = pending_df.iloc[start:start + BATCH_SIZE].copy()
    batch_ids = batch_df["row_id"].astype(int).tolist()

    outputs = generate_batch(batch_df)

    if outputs is not None:
        generated_rows.extend(outputs)

        temp_df = pd.DataFrame(generated_rows)

        if not temp_df.empty:
            temp_df["row_id"] = temp_df["row_id"].astype(int)
            temp_df = temp_df.drop_duplicates(subset=["row_id"], keep="last")
            temp_df = temp_df.sort_values("row_id").reset_index(drop=True)

            generated_rows = temp_df.to_dict("records")

            temp_df.to_csv(PARTIAL_GENERATED_CSV, index=False)
            print(f"Saved partial generated rows: {len(temp_df)}")

    else:
        print(f"Batch failed after all retries: {batch_ids}")

        failed_batches.append({
            "start_index": int(start),
            "row_ids": json.dumps(batch_ids),
            "status": "failed_after_retries",
        })

        pd.DataFrame(failed_batches).to_csv(FAILED_BATCHES_CSV, index=False)

    time.sleep(SLEEP_SECONDS)

generated_df = pd.DataFrame(generated_rows)

if not generated_df.empty:
    generated_df["row_id"] = generated_df["row_id"].astype(int)
    generated_df = generated_df.drop_duplicates(subset=["row_id"], keep="last")
    generated_df = generated_df.sort_values("row_id").reset_index(drop=True)

print("Generated rows:", len(generated_df))
display(generated_df.head())

if failed_batches:
    print("Some batches failed. Saved failed batch list to:")
    print(FAILED_BATCHES_CSV)
else:
    print("No failed batches.")

Resuming from partial. Already generated: 15380
Total target rows: 25000
Already done: 15380
Pending rows: 9620

  0%|          | 0/962 [00:00<?, ?it/s]

Saved partial generated rows: 15390

  0%|          | 1/962 [00:07<1:54:00,  7.12s/it]

Saved partial generated rows: 15400

  0%|          | 2/962 [00:13<1:48:44,  6.80s/it]

Saved partial generated rows: 15410

  0%|          | 3/962 [00:20<1:46:49,  6.68s/it]

Saved partial generated rows: 15420

  0%|          | 4/962 [00:26<1:41:08,  6.33s/it]

Saved partial generated rows: 15430

  1%|          | 5/962 [00:33<1:45:26,  6.61s/it]

Saved partial generated rows: 15440

  1%|          | 6/962 [00:40<1:49:25,  6.87s/it]

Saved partial generated rows: 15450

  1%|          | 7/962 [00:46<1:43:21,  6.49s/it]

Saved partial generated rows: 15460

  1%|          | 8/962 [00:53<1:46:52,  6.72s/it]

Saved partial generated rows: 15470

  1%|          | 9/962 [01:00<1:48:47,  6.85s/it]

Saved partial generated rows: 15480

  1%|          | 10/962 [01:06<1:45:37,  6.66s/it]

Saved partial generated rows: 15490

  1%|          | 11/962 [01:13<1:46:38,  6.73s/it]

Saved partial generated rows: 15500

  1%|          | 12/962 [01:19<1:43:32,  6.54s/it]

Saved partial generated rows: 15510

  1%|▏         | 13/962 [01:25<1:39:20,  6.28s/it]

Saved partial generated rows: 15520

  1%|▏         | 14/962 [01:33<1:45:19,  6.67s/it]

Saved partial generated rows: 15530

  2%|▏         | 15/962 [01:39<1:44:08,  6.60s/it]

Saved partial generated rows: 15540

  2%|▏         | 16/962 [01:46<1:45:21,  6.68s/it]

Saved partial generated rows: 15550

  2%|▏         | 17/962 [01:52<1:41:30,  6.45s/it]

Saved partial generated rows: 15560

  2%|▏         | 18/962 [01:58<1:40:21,  6.38s/it]

Saved partial generated rows: 15570

  2%|▏         | 19/962 [02:05<1:41:03,  6.43s/it]

Saved partial generated rows: 15580

  2%|▏         | 20/962 [02:11<1:40:47,  6.42s/it]

Saved partial generated rows: 15590

  2%|▏         | 21/962 [02:18<1:44:03,  6.63s/it]

Saved partial generated rows: 15600

  2%|▏         | 22/962 [02:24<1:41:52,  6.50s/it]

Saved partial generated rows: 15610

  2%|▏         | 23/962 [02:30<1:39:16,  6.34s/it]

Saved partial generated rows: 15620

  2%|▏         | 24/962 [02:37<1:39:46,  6.38s/it]

Saved partial generated rows: 15630

  3%|▎         | 25/962 [02:42<1:36:16,  6.17s/it]

Saved partial generated rows: 15640

  3%|▎         | 26/962 [02:48<1:34:45,  6.07s/it]

Saved partial generated rows: 15650

  3%|▎         | 27/962 [02:55<1:39:24,  6.38s/it]

Saved partial generated rows: 15660

  3%|▎         | 28/962 [03:02<1:40:17,  6.44s/it]

Saved partial generated rows: 15670

  3%|▎         | 29/962 [03:09<1:42:07,  6.57s/it]

Saved partial generated rows: 15680

  3%|▎         | 30/962 [03:15<1:38:33,  6.35s/it]

Saved partial generated rows: 15690

  3%|▎         | 31/962 [03:21<1:39:17,  6.40s/it]

Saved partial generated rows: 15700

  3%|▎         | 32/962 [03:28<1:40:59,  6.52s/it]

Saved partial generated rows: 15710

  3%|▎         | 33/962 [03:34<1:37:19,  6.29s/it]

Saved partial generated rows: 15720

  4%|▎         | 34/962 [03:40<1:37:07,  6.28s/it]

Saved partial generated rows: 15730

  4%|▎         | 35/962 [03:48<1:44:45,  6.78s/it]

Saved partial generated rows: 15740

  4%|▎         | 36/962 [03:56<1:50:31,  7.16s/it]

Saved partial generated rows: 15750

  4%|▍         | 37/962 [04:02<1:47:26,  6.97s/it]

Saved partial generated rows: 15760

  4%|▍         | 38/962 [04:09<1:45:32,  6.85s/it]

Saved partial generated rows: 15770

  4%|▍         | 39/962 [04:15<1:41:06,  6.57s/it]

Saved partial generated rows: 15780

  4%|▍         | 40/962 [04:22<1:41:01,  6.57s/it]

Saved partial generated rows: 15790

  4%|▍         | 41/962 [04:28<1:39:44,  6.50s/it]

Saved partial generated rows: 15800

  4%|▍         | 42/962 [04:33<1:35:28,  6.23s/it]

Saved partial generated rows: 15810

  4%|▍         | 43/962 [04:39<1:31:59,  6.01s/it]

Saved partial generated rows: 15820

  5%|▍         | 44/962 [04:45<1:32:59,  6.08s/it]

Saved partial generated rows: 15830

  5%|▍         | 45/962 [04:51<1:33:52,  6.14s/it]

Saved partial generated rows: 15840

  5%|▍         | 46/962 [04:57<1:32:33,  6.06s/it]

Saved partial generated rows: 15850

  5%|▍         | 47/962 [05:03<1:32:48,  6.09s/it]

Saved partial generated rows: 15860

  5%|▍         | 48/962 [05:10<1:36:33,  6.34s/it]

Saved partial generated rows: 15870

  5%|▌         | 49/962 [05:16<1:33:16,  6.13s/it]

Saved partial generated rows: 15880

  5%|▌         | 50/962 [05:22<1:30:25,  5.95s/it]

Saved partial generated rows: 15890

  5%|▌         | 51/962 [05:27<1:29:35,  5.90s/it]

Saved partial generated rows: 15900

  5%|▌         | 52/962 [05:33<1:30:11,  5.95s/it]

Saved partial generated rows: 15910

  6%|▌         | 53/962 [05:39<1:30:41,  5.99s/it]

Saved partial generated rows: 15920

  6%|▌         | 54/962 [05:47<1:35:19,  6.30s/it]

Saved partial generated rows: 15930

  6%|▌         | 55/962 [05:53<1:34:45,  6.27s/it]

Saved partial generated rows: 15940

  6%|▌         | 56/962 [05:59<1:32:44,  6.14s/it]

Saved partial generated rows: 15950

  6%|▌         | 57/962 [06:05<1:36:01,  6.37s/it]

Saved partial generated rows: 15960

  6%|▌         | 58/962 [06:12<1:36:33,  6.41s/it]

Saved partial generated rows: 15970

  6%|▌         | 59/962 [06:18<1:32:41,  6.16s/it]

Saved partial generated rows: 15980

  6%|▌         | 60/962 [06:25<1:36:48,  6.44s/it]

Saved partial generated rows: 15990

  6%|▋         | 61/962 [06:31<1:34:53,  6.32s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 6.6 seconds before retrying...
Saved partial generated rows: 16000

  6%|▋         | 62/962 [06:44<2:08:22,  8.56s/it]

Saved partial generated rows: 16010

  7%|▋         | 63/962 [06:51<1:58:50,  7.93s/it]

Saved partial generated rows: 16020

  7%|▋         | 64/962 [06:59<2:00:45,  8.07s/it]

Saved partial generated rows: 16030

  7%|▋         | 65/962 [07:06<1:52:16,  7.51s/it]

Saved partial generated rows: 16040

  7%|▋         | 66/962 [07:18<2:13:46,  8.96s/it]

Saved partial generated rows: 16050

  7%|▋         | 67/962 [07:25<2:03:25,  8.27s/it]

Saved partial generated rows: 16060

  7%|▋         | 68/962 [07:31<1:53:10,  7.60s/it]

Saved partial generated rows: 16070

  7%|▋         | 69/962 [07:37<1:46:29,  7.15s/it]

Saved partial generated rows: 16080

  7%|▋         | 70/962 [07:42<1:40:28,  6.76s/it]

Saved partial generated rows: 16090

  7%|▋         | 71/962 [07:49<1:40:57,  6.80s/it]

Saved partial generated rows: 16100

  7%|▋         | 72/962 [07:56<1:38:19,  6.63s/it]

Saved partial generated rows: 16110

  8%|▊         | 73/962 [08:02<1:35:24,  6.44s/it]

Saved partial generated rows: 16120

  8%|▊         | 74/962 [08:08<1:33:55,  6.35s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 5.7 seconds before retrying...
Saved partial generated rows: 16130

  8%|▊         | 75/962 [08:23<2:13:54,  9.06s/it]

Saved partial generated rows: 16140

  8%|▊         | 76/962 [08:30<2:03:08,  8.34s/it]

Saved partial generated rows: 16150

  8%|▊         | 77/962 [08:37<1:55:53,  7.86s/it]

Saved partial generated rows: 16160

  8%|▊         | 78/962 [08:42<1:45:33,  7.16s/it]

Saved partial generated rows: 16170

  8%|▊         | 79/962 [08:50<1:47:11,  7.28s/it]

Saved partial generated rows: 16180

  8%|▊         | 80/962 [08:58<1:51:21,  7.57s/it]

Saved partial generated rows: 16190

  8%|▊         | 81/962 [09:05<1:48:36,  7.40s/it]

Saved partial generated rows: 16200

  9%|▊         | 82/962 [09:11<1:42:33,  6.99s/it]

Saved partial generated rows: 16210

  9%|▊         | 83/962 [09:19<1:48:45,  7.42s/it]

Saved partial generated rows: 16220

  9%|▊         | 84/962 [09:26<1:44:41,  7.15s/it]

Saved partial generated rows: 16230

  9%|▉         | 85/962 [09:33<1:44:31,  7.15s/it]

Saved partial generated rows: 16240

  9%|▉         | 86/962 [09:44<2:02:02,  8.36s/it]

Saved partial generated rows: 16250

  9%|▉         | 87/962 [09:51<1:54:30,  7.85s/it]

Saved partial generated rows: 16260

  9%|▉         | 88/962 [09:57<1:47:21,  7.37s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 6.0 seconds before retrying...
Saved partial generated rows: 16270

  9%|▉         | 89/962 [10:11<2:16:12,  9.36s/it]

Saved partial generated rows: 16280

  9%|▉         | 90/962 [10:18<2:03:24,  8.49s/it]

Saved partial generated rows: 16290

  9%|▉         | 91/962 [10:25<1:58:25,  8.16s/it]

Saved partial generated rows: 16300

 10%|▉         | 92/962 [10:31<1:49:28,  7.55s/it]

Saved partial generated rows: 16310

 10%|▉         | 93/962 [10:37<1:41:00,  6.97s/it]

Saved partial generated rows: 16320

 10%|▉         | 94/962 [10:43<1:38:04,  6.78s/it]

Saved partial generated rows: 16330

 10%|▉         | 95/962 [10:50<1:37:07,  6.72s/it]

Saved partial generated rows: 16340

 10%|▉         | 96/962 [10:55<1:32:43,  6.42s/it]

Saved partial generated rows: 16350

 10%|█         | 97/962 [11:03<1:36:20,  6.68s/it]

Saved partial generated rows: 16360

 10%|█         | 98/962 [11:08<1:30:02,  6.25s/it]

Saved partial generated rows: 16370

 10%|█         | 99/962 [11:15<1:31:33,  6.37s/it]

Saved partial generated rows: 16380

 10%|█         | 100/962 [11:23<1:39:19,  6.91s/it]

Saved partial generated rows: 16390

 10%|█         | 101/962 [11:29<1:35:53,  6.68s/it]

Saved partial generated rows: 16400

 11%|█         | 102/962 [11:36<1:38:05,  6.84s/it]

Saved partial generated rows: 16410

 11%|█         | 103/962 [11:43<1:38:42,  6.90s/it]

Saved partial generated rows: 16420

 11%|█         | 104/962 [11:49<1:35:49,  6.70s/it]

Saved partial generated rows: 16430

 11%|█         | 105/962 [11:57<1:38:49,  6.92s/it]

Saved partial generated rows: 16440

 11%|█         | 106/962 [12:03<1:35:35,  6.70s/it]

Saved partial generated rows: 16450

 11%|█         | 107/962 [12:09<1:31:47,  6.44s/it]

Generation attempt 1/8 failed.
Error: ValueError('Missing row_id(s) in response: [16453]')
Waiting 5.5 seconds before retrying...
Saved partial generated rows: 16460

 11%|█         | 108/962 [12:25<2:12:23,  9.30s/it]

Saved partial generated rows: 16470

 11%|█▏        | 109/962 [12:34<2:11:50,  9.27s/it]

Saved partial generated rows: 16480

 11%|█▏        | 110/962 [12:41<2:00:32,  8.49s/it]

Saved partial generated rows: 16490

 12%|█▏        | 111/962 [12:47<1:49:38,  7.73s/it]

Saved partial generated rows: 16500

 12%|█▏        | 112/962 [12:53<1:45:45,  7.47s/it]

Saved partial generated rows: 16510

 12%|█▏        | 113/962 [13:00<1:42:02,  7.21s/it]

Saved partial generated rows: 16520

 12%|█▏        | 114/962 [13:07<1:40:37,  7.12s/it]

Saved partial generated rows: 16530

 12%|█▏        | 115/962 [13:13<1:35:32,  6.77s/it]

Saved partial generated rows: 16540

 12%|█▏        | 116/962 [13:18<1:29:52,  6.37s/it]

Saved partial generated rows: 16550

 12%|█▏        | 117/962 [13:25<1:29:31,  6.36s/it]

Saved partial generated rows: 16560

 12%|█▏        | 118/962 [13:30<1:25:27,  6.08s/it]

Saved partial generated rows: 16570

 12%|█▏        | 119/962 [13:36<1:24:47,  6.03s/it]

Saved partial generated rows: 16580

 12%|█▏        | 120/962 [13:43<1:27:17,  6.22s/it]

Saved partial generated rows: 16590

 13%|█▎        | 121/962 [13:51<1:33:51,  6.70s/it]

Saved partial generated rows: 16600

 13%|█▎        | 122/962 [13:56<1:30:27,  6.46s/it]

Saved partial generated rows: 16610

 13%|█▎        | 123/962 [14:03<1:30:45,  6.49s/it]

Saved partial generated rows: 16620

 13%|█▎        | 124/962 [14:09<1:28:46,  6.36s/it]

Saved partial generated rows: 16630

 13%|█▎        | 125/962 [14:15<1:29:04,  6.39s/it]

Saved partial generated rows: 16640

 13%|█▎        | 126/962 [14:21<1:25:46,  6.16s/it]

Saved partial generated rows: 16650

 13%|█▎        | 127/962 [14:28<1:28:10,  6.34s/it]

Saved partial generated rows: 16660

 13%|█▎        | 128/962 [14:35<1:29:52,  6.47s/it]

Saved partial generated rows: 16670

 13%|█▎        | 129/962 [14:41<1:30:59,  6.55s/it]

Saved partial generated rows: 16680

 14%|█▎        | 130/962 [14:50<1:37:30,  7.03s/it]

Saved partial generated rows: 16690

 14%|█▎        | 131/962 [14:55<1:32:50,  6.70s/it]

Saved partial generated rows: 16700

 14%|█▎        | 132/962 [15:03<1:35:14,  6.88s/it]

Saved partial generated rows: 16710

 14%|█▍        | 133/962 [15:09<1:33:24,  6.76s/it]

Saved partial generated rows: 16720

 14%|█▍        | 134/962 [15:15<1:28:27,  6.41s/it]

Saved partial generated rows: 16730

 14%|█▍        | 135/962 [15:20<1:24:51,  6.16s/it]

Saved partial generated rows: 16740

 14%|█▍        | 136/962 [15:27<1:24:39,  6.15s/it]

Saved partial generated rows: 16750

 14%|█▍        | 137/962 [15:33<1:27:24,  6.36s/it]

Saved partial generated rows: 16760

 14%|█▍        | 138/962 [15:40<1:26:35,  6.31s/it]

Saved partial generated rows: 16770

 14%|█▍        | 139/962 [15:46<1:26:12,  6.29s/it]

Saved partial generated rows: 16780

 15%|█▍        | 140/962 [15:53<1:27:48,  6.41s/it]

Saved partial generated rows: 16790

 15%|█▍        | 141/962 [15:59<1:27:58,  6.43s/it]

Saved partial generated rows: 16800

 15%|█▍        | 142/962 [16:06<1:31:53,  6.72s/it]

Saved partial generated rows: 16810

 15%|█▍        | 143/962 [16:12<1:28:17,  6.47s/it]

Saved partial generated rows: 16820

 15%|█▍        | 144/962 [16:18<1:27:04,  6.39s/it]

Saved partial generated rows: 16830

 15%|█▌        | 145/962 [16:25<1:26:40,  6.37s/it]

Saved partial generated rows: 16840

 15%|█▌        | 146/962 [16:32<1:30:03,  6.62s/it]

Saved partial generated rows: 16850

 15%|█▌        | 147/962 [16:39<1:30:06,  6.63s/it]

Saved partial generated rows: 16860

 15%|█▌        | 148/962 [16:45<1:30:42,  6.69s/it]

Saved partial generated rows: 16870

 15%|█▌        | 149/962 [16:53<1:33:22,  6.89s/it]

Saved partial generated rows: 16880

 16%|█▌        | 150/962 [16:59<1:32:12,  6.81s/it]

Saved partial generated rows: 16890

 16%|█▌        | 151/962 [17:07<1:36:02,  7.10s/it]

Saved partial generated rows: 16900

 16%|█▌        | 152/962 [17:16<1:44:20,  7.73s/it]

Saved partial generated rows: 16910

 16%|█▌        | 153/962 [17:25<1:46:07,  7.87s/it]

Saved partial generated rows: 16920

 16%|█▌        | 154/962 [17:32<1:43:07,  7.66s/it]

Saved partial generated rows: 16930

 16%|█▌        | 155/962 [17:39<1:40:40,  7.49s/it]

Saved partial generated rows: 16940

 16%|█▌        | 156/962 [17:45<1:35:30,  7.11s/it]

Saved partial generated rows: 16950

 16%|█▋        | 157/962 [17:51<1:30:39,  6.76s/it]

Saved partial generated rows: 16960

 16%|█▋        | 158/962 [17:59<1:34:03,  7.02s/it]

Saved partial generated rows: 16970

 17%|█▋        | 159/962 [18:05<1:29:49,  6.71s/it]

Saved partial generated rows: 16980

 17%|█▋        | 160/962 [18:11<1:27:20,  6.53s/it]

Saved partial generated rows: 16990

 17%|█▋        | 161/962 [18:17<1:27:46,  6.58s/it]

Saved partial generated rows: 17000

 17%|█▋        | 162/962 [18:24<1:27:51,  6.59s/it]

Saved partial generated rows: 17010

 17%|█▋        | 163/962 [18:30<1:26:13,  6.47s/it]

Saved partial generated rows: 17020

 17%|█▋        | 164/962 [18:36<1:24:50,  6.38s/it]

Saved partial generated rows: 17030

 17%|█▋        | 165/962 [18:43<1:25:42,  6.45s/it]

Saved partial generated rows: 17040

 17%|█▋        | 166/962 [18:49<1:23:58,  6.33s/it]

Saved partial generated rows: 17050

 17%|█▋        | 167/962 [18:56<1:27:20,  6.59s/it]

Saved partial generated rows: 17060

 17%|█▋        | 168/962 [19:03<1:27:44,  6.63s/it]

Saved partial generated rows: 17070

 18%|█▊        | 169/962 [19:09<1:26:56,  6.58s/it]

Saved partial generated rows: 17080

 18%|█▊        | 170/962 [19:16<1:25:30,  6.48s/it]

Saved partial generated rows: 17090

 18%|█▊        | 171/962 [19:23<1:27:45,  6.66s/it]

Saved partial generated rows: 17100

 18%|█▊        | 172/962 [19:29<1:25:51,  6.52s/it]

Saved partial generated rows: 17110

 18%|█▊        | 173/962 [19:35<1:24:48,  6.45s/it]

Saved partial generated rows: 17120

 18%|█▊        | 174/962 [19:42<1:26:43,  6.60s/it]

Saved partial generated rows: 17130

 18%|█▊        | 175/962 [19:49<1:27:13,  6.65s/it]

Saved partial generated rows: 17140

 18%|█▊        | 176/962 [19:56<1:27:32,  6.68s/it]

Saved partial generated rows: 17150

 18%|█▊        | 177/962 [20:02<1:27:24,  6.68s/it]

Saved partial generated rows: 17160

 19%|█▊        | 178/962 [20:10<1:29:31,  6.85s/it]

Saved partial generated rows: 17170

 19%|█▊        | 179/962 [20:16<1:28:15,  6.76s/it]

Saved partial generated rows: 17180

 19%|█▊        | 180/962 [20:22<1:23:05,  6.38s/it]

Saved partial generated rows: 17190

 19%|█▉        | 181/962 [20:29<1:24:42,  6.51s/it]

Saved partial generated rows: 17200

 19%|█▉        | 182/962 [20:35<1:24:46,  6.52s/it]

Saved partial generated rows: 17210

 19%|█▉        | 183/962 [20:41<1:23:12,  6.41s/it]

Saved partial generated rows: 17220

 19%|█▉        | 184/962 [20:48<1:25:15,  6.58s/it]

Saved partial generated rows: 17230

 19%|█▉        | 185/962 [20:54<1:22:40,  6.38s/it]

Saved partial generated rows: 17240

 19%|█▉        | 186/962 [21:02<1:26:48,  6.71s/it]

Saved partial generated rows: 17250

 19%|█▉        | 187/962 [21:08<1:25:35,  6.63s/it]

Saved partial generated rows: 17260

 20%|█▉        | 188/962 [21:14<1:23:07,  6.44s/it]

Saved partial generated rows: 17270

 20%|█▉        | 189/962 [21:20<1:21:15,  6.31s/it]

Saved partial generated rows: 17280

 20%|█▉        | 190/962 [21:26<1:19:20,  6.17s/it]

Saved partial generated rows: 17290

 20%|█▉        | 191/962 [21:32<1:19:57,  6.22s/it]

Saved partial generated rows: 17300

 20%|█▉        | 192/962 [21:40<1:24:28,  6.58s/it]

Saved partial generated rows: 17310

 20%|██        | 193/962 [21:46<1:22:30,  6.44s/it]

Saved partial generated rows: 17320

 20%|██        | 194/962 [21:53<1:24:42,  6.62s/it]

Saved partial generated rows: 17330

 20%|██        | 195/962 [21:59<1:24:42,  6.63s/it]

Saved partial generated rows: 17340

 20%|██        | 196/962 [22:06<1:23:48,  6.56s/it]

Saved partial generated rows: 17350

 20%|██        | 197/962 [22:12<1:23:36,  6.56s/it]

Saved partial generated rows: 17360

 21%|██        | 198/962 [22:18<1:20:16,  6.30s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 6.1 seconds before retrying...
Saved partial generated rows: 17370

 21%|██        | 199/962 [22:33<1:53:34,  8.93s/it]

Saved partial generated rows: 17380

 21%|██        | 200/962 [22:39<1:42:43,  8.09s/it]

Saved partial generated rows: 17390

 21%|██        | 201/962 [22:46<1:36:25,  7.60s/it]

Saved partial generated rows: 17400

 21%|██        | 202/962 [22:52<1:31:31,  7.23s/it]

Saved partial generated rows: 17410

 21%|██        | 203/962 [22:59<1:29:14,  7.05s/it]

Saved partial generated rows: 17420

 21%|██        | 204/962 [23:06<1:28:46,  7.03s/it]

Saved partial generated rows: 17430

 21%|██▏       | 205/962 [23:11<1:23:43,  6.64s/it]

Saved partial generated rows: 17440

 21%|██▏       | 206/962 [23:18<1:22:10,  6.52s/it]

Saved partial generated rows: 17450

 22%|██▏       | 207/962 [23:23<1:16:47,  6.10s/it]

Saved partial generated rows: 17460

 22%|██▏       | 208/962 [23:28<1:14:54,  5.96s/it]

Saved partial generated rows: 17470

 22%|██▏       | 209/962 [23:35<1:18:11,  6.23s/it]

Saved partial generated rows: 17480

 22%|██▏       | 210/962 [23:42<1:19:45,  6.36s/it]

Saved partial generated rows: 17490

 22%|██▏       | 211/962 [23:48<1:18:08,  6.24s/it]

Saved partial generated rows: 17500

 22%|██▏       | 212/962 [23:54<1:18:17,  6.26s/it]

Saved partial generated rows: 17510

 22%|██▏       | 213/962 [24:00<1:17:07,  6.18s/it]

Saved partial generated rows: 17520

 22%|██▏       | 214/962 [24:07<1:17:54,  6.25s/it]

Saved partial generated rows: 17530

 22%|██▏       | 215/962 [24:13<1:18:33,  6.31s/it]

Saved partial generated rows: 17540

 22%|██▏       | 216/962 [24:21<1:23:10,  6.69s/it]

Saved partial generated rows: 17550

 23%|██▎       | 217/962 [24:28<1:24:02,  6.77s/it]

Saved partial generated rows: 17560

 23%|██▎       | 218/962 [24:35<1:26:36,  6.98s/it]

Saved partial generated rows: 17570

 23%|██▎       | 219/962 [24:41<1:24:07,  6.79s/it]

Saved partial generated rows: 17580

 23%|██▎       | 220/962 [24:47<1:19:14,  6.41s/it]

Saved partial generated rows: 17590

 23%|██▎       | 221/962 [24:54<1:20:04,  6.48s/it]

Saved partial generated rows: 17600

 23%|██▎       | 222/962 [25:00<1:20:28,  6.53s/it]

Saved partial generated rows: 17610

 23%|██▎       | 223/962 [25:07<1:19:28,  6.45s/it]

Saved partial generated rows: 17620

 23%|██▎       | 224/962 [25:13<1:20:30,  6.55s/it]

Saved partial generated rows: 17630

 23%|██▎       | 225/962 [25:20<1:21:47,  6.66s/it]

Saved partial generated rows: 17640

 23%|██▎       | 226/962 [25:27<1:22:26,  6.72s/it]

Saved partial generated rows: 17650

 24%|██▎       | 227/962 [25:34<1:23:30,  6.82s/it]

Saved partial generated rows: 17660

 24%|██▎       | 228/962 [25:41<1:23:11,  6.80s/it]

Saved partial generated rows: 17670

 24%|██▍       | 229/962 [25:47<1:20:57,  6.63s/it]

Saved partial generated rows: 17680

 24%|██▍       | 230/962 [25:54<1:20:08,  6.57s/it]

Saved partial generated rows: 17690

 24%|██▍       | 231/962 [25:59<1:16:56,  6.32s/it]

Saved partial generated rows: 17700

 24%|██▍       | 232/962 [26:07<1:21:32,  6.70s/it]

Saved partial generated rows: 17710

 24%|██▍       | 233/962 [26:13<1:20:23,  6.62s/it]

Saved partial generated rows: 17720

 24%|██▍       | 234/962 [26:20<1:19:55,  6.59s/it]

Saved partial generated rows: 17730

 24%|██▍       | 235/962 [26:27<1:21:26,  6.72s/it]

Saved partial generated rows: 17740

 25%|██▍       | 236/962 [26:34<1:24:04,  6.95s/it]

Saved partial generated rows: 17750

 25%|██▍       | 237/962 [26:41<1:23:05,  6.88s/it]

Saved partial generated rows: 17760

 25%|██▍       | 238/962 [26:48<1:24:57,  7.04s/it]

Saved partial generated rows: 17770

 25%|██▍       | 239/962 [26:54<1:19:54,  6.63s/it]

Saved partial generated rows: 17780

 25%|██▍       | 240/962 [27:02<1:22:22,  6.85s/it]

Saved partial generated rows: 17790

 25%|██▌       | 241/962 [27:08<1:21:10,  6.75s/it]

Saved partial generated rows: 17800

 25%|██▌       | 242/962 [27:15<1:21:24,  6.78s/it]

Saved partial generated rows: 17810

 25%|██▌       | 243/962 [27:21<1:18:59,  6.59s/it]

Saved partial generated rows: 17820

 25%|██▌       | 244/962 [27:27<1:18:00,  6.52s/it]

Saved partial generated rows: 17830

 25%|██▌       | 245/962 [27:34<1:17:30,  6.49s/it]

Saved partial generated rows: 17840

 26%|██▌       | 246/962 [27:41<1:18:37,  6.59s/it]

Saved partial generated rows: 17850

 26%|██▌       | 247/962 [27:47<1:18:17,  6.57s/it]

Saved partial generated rows: 17860

 26%|██▌       | 248/962 [27:54<1:18:07,  6.57s/it]

Saved partial generated rows: 17870

 26%|██▌       | 249/962 [28:00<1:15:14,  6.33s/it]

Saved partial generated rows: 17880

 26%|██▌       | 250/962 [28:05<1:12:49,  6.14s/it]

Saved partial generated rows: 17890

 26%|██▌       | 251/962 [28:12<1:13:41,  6.22s/it]

Saved partial generated rows: 17900

 26%|██▌       | 252/962 [28:18<1:13:27,  6.21s/it]

Saved partial generated rows: 17910

 26%|██▋       | 253/962 [28:24<1:12:46,  6.16s/it]

Saved partial generated rows: 17920

 26%|██▋       | 254/962 [28:30<1:13:42,  6.25s/it]

Saved partial generated rows: 17930

 27%|██▋       | 255/962 [28:36<1:12:44,  6.17s/it]

Saved partial generated rows: 17940

 27%|██▋       | 256/962 [28:42<1:10:52,  6.02s/it]

Saved partial generated rows: 17950

 27%|██▋       | 257/962 [28:49<1:12:38,  6.18s/it]

Saved partial generated rows: 17960

 27%|██▋       | 258/962 [28:55<1:13:28,  6.26s/it]

Saved partial generated rows: 17970

 27%|██▋       | 259/962 [29:01<1:12:37,  6.20s/it]

Saved partial generated rows: 17980

 27%|██▋       | 260/962 [29:07<1:10:52,  6.06s/it]

Saved partial generated rows: 17990

 27%|██▋       | 261/962 [29:14<1:13:56,  6.33s/it]

Saved partial generated rows: 18000

 27%|██▋       | 262/962 [29:21<1:16:03,  6.52s/it]

Saved partial generated rows: 18010

 27%|██▋       | 263/962 [29:29<1:22:25,  7.08s/it]

Saved partial generated rows: 18020

 27%|██▋       | 264/962 [29:37<1:23:47,  7.20s/it]

Saved partial generated rows: 18030

 28%|██▊       | 265/962 [29:43<1:21:02,  6.98s/it]

Saved partial generated rows: 18040

 28%|██▊       | 266/962 [29:50<1:20:53,  6.97s/it]

Saved partial generated rows: 18050

 28%|██▊       | 267/962 [29:56<1:18:54,  6.81s/it]

Saved partial generated rows: 18060

 28%|██▊       | 268/962 [30:02<1:14:43,  6.46s/it]

Saved partial generated rows: 18070

 28%|██▊       | 269/962 [30:09<1:17:59,  6.75s/it]

Saved partial generated rows: 18080

 28%|██▊       | 270/962 [30:17<1:19:06,  6.86s/it]

Saved partial generated rows: 18090

 28%|██▊       | 271/962 [30:23<1:18:38,  6.83s/it]

Saved partial generated rows: 18100

 28%|██▊       | 272/962 [30:35<1:34:32,  8.22s/it]

Saved partial generated rows: 18110

 28%|██▊       | 273/962 [30:42<1:30:04,  7.84s/it]

Saved partial generated rows: 18120

 28%|██▊       | 274/962 [30:51<1:34:39,  8.26s/it]

Saved partial generated rows: 18130

 29%|██▊       | 275/962 [30:57<1:26:33,  7.56s/it]

Saved partial generated rows: 18140

 29%|██▊       | 276/962 [31:03<1:21:34,  7.14s/it]

Saved partial generated rows: 18150

 29%|██▉       | 277/962 [31:15<1:38:04,  8.59s/it]

Saved partial generated rows: 18160

 29%|██▉       | 278/962 [31:26<1:46:56,  9.38s/it]

Saved partial generated rows: 18170

 29%|██▉       | 279/962 [31:34<1:40:45,  8.85s/it]

Saved partial generated rows: 18180

 29%|██▉       | 280/962 [31:41<1:33:26,  8.22s/it]

Saved partial generated rows: 18190

 29%|██▉       | 281/962 [31:50<1:37:46,  8.61s/it]

Saved partial generated rows: 18200

 29%|██▉       | 282/962 [31:57<1:32:43,  8.18s/it]

Saved partial generated rows: 18210

 29%|██▉       | 283/962 [32:04<1:26:00,  7.60s/it]

Saved partial generated rows: 18220

 30%|██▉       | 284/962 [32:12<1:28:24,  7.82s/it]

Saved partial generated rows: 18230

 30%|██▉       | 285/962 [32:20<1:29:41,  7.95s/it]

Saved partial generated rows: 18240

 30%|██▉       | 286/962 [32:30<1:36:56,  8.60s/it]

Saved partial generated rows: 18250

 30%|██▉       | 287/962 [32:39<1:37:08,  8.63s/it]

Saved partial generated rows: 18260

 30%|██▉       | 288/962 [32:47<1:34:07,  8.38s/it]

Saved partial generated rows: 18270

 30%|███       | 289/962 [32:54<1:29:14,  7.96s/it]

Saved partial generated rows: 18280

 30%|███       | 290/962 [33:02<1:31:34,  8.18s/it]

Saved partial generated rows: 18290

 30%|███       | 291/962 [33:12<1:35:48,  8.57s/it]

Saved partial generated rows: 18300

 30%|███       | 292/962 [33:20<1:34:48,  8.49s/it]

Saved partial generated rows: 18310

 30%|███       | 293/962 [33:30<1:37:55,  8.78s/it]

Saved partial generated rows: 18320

 31%|███       | 294/962 [33:37<1:33:43,  8.42s/it]

Saved partial generated rows: 18330

 31%|███       | 295/962 [33:43<1:25:31,  7.69s/it]

Saved partial generated rows: 18340

 31%|███       | 296/962 [33:49<1:20:03,  7.21s/it]

Saved partial generated rows: 18350

 31%|███       | 297/962 [33:56<1:18:24,  7.07s/it]

Saved partial generated rows: 18360

 31%|███       | 298/962 [34:02<1:15:39,  6.84s/it]

Saved partial generated rows: 18370

 31%|███       | 299/962 [34:10<1:18:55,  7.14s/it]

Saved partial generated rows: 18380

 31%|███       | 300/962 [34:16<1:13:27,  6.66s/it]

Saved partial generated rows: 18390

 31%|███▏      | 301/962 [34:22<1:12:19,  6.56s/it]

Saved partial generated rows: 18400

 31%|███▏      | 302/962 [34:28<1:10:49,  6.44s/it]

Saved partial generated rows: 18410

 31%|███▏      | 303/962 [34:34<1:09:34,  6.33s/it]

Saved partial generated rows: 18420

 32%|███▏      | 304/962 [34:40<1:08:15,  6.22s/it]

Saved partial generated rows: 18430

 32%|███▏      | 305/962 [34:47<1:09:10,  6.32s/it]

Saved partial generated rows: 18440

 32%|███▏      | 306/962 [34:53<1:07:56,  6.21s/it]

Saved partial generated rows: 18450

 32%|███▏      | 307/962 [34:59<1:08:40,  6.29s/it]

Saved partial generated rows: 18460

 32%|███▏      | 308/962 [35:06<1:08:46,  6.31s/it]

Saved partial generated rows: 18470

 32%|███▏      | 309/962 [35:12<1:09:27,  6.38s/it]

Saved partial generated rows: 18480

 32%|███▏      | 310/962 [35:18<1:08:34,  6.31s/it]

Saved partial generated rows: 18490

 32%|███▏      | 311/962 [35:24<1:07:35,  6.23s/it]

Saved partial generated rows: 18500

 32%|███▏      | 312/962 [35:31<1:09:47,  6.44s/it]

Saved partial generated rows: 18510

 33%|███▎      | 313/962 [35:37<1:08:32,  6.34s/it]

Saved partial generated rows: 18520

 33%|███▎      | 314/962 [35:45<1:12:22,  6.70s/it]

Saved partial generated rows: 18530

 33%|███▎      | 315/962 [35:51<1:10:28,  6.54s/it]

Saved partial generated rows: 18540

 33%|███▎      | 316/962 [35:57<1:09:23,  6.44s/it]

Saved partial generated rows: 18550

 33%|███▎      | 317/962 [36:04<1:08:41,  6.39s/it]

Saved partial generated rows: 18560

 33%|███▎      | 318/962 [36:11<1:11:44,  6.68s/it]

Saved partial generated rows: 18570

 33%|███▎      | 319/962 [36:17<1:09:53,  6.52s/it]

Saved partial generated rows: 18580

 33%|███▎      | 320/962 [36:24<1:12:11,  6.75s/it]

Saved partial generated rows: 18590

 33%|███▎      | 321/962 [36:32<1:13:25,  6.87s/it]

Saved partial generated rows: 18600

 33%|███▎      | 322/962 [36:39<1:16:33,  7.18s/it]

Saved partial generated rows: 18610

 34%|███▎      | 323/962 [36:47<1:19:01,  7.42s/it]

Saved partial generated rows: 18620

 34%|███▎      | 324/962 [36:55<1:20:03,  7.53s/it]

Saved partial generated rows: 18630

 34%|███▍      | 325/962 [37:01<1:13:53,  6.96s/it]

Saved partial generated rows: 18640

 34%|███▍      | 326/962 [37:07<1:11:10,  6.72s/it]

Saved partial generated rows: 18650

 34%|███▍      | 327/962 [37:14<1:12:30,  6.85s/it]

Saved partial generated rows: 18660

 34%|███▍      | 328/962 [37:20<1:10:29,  6.67s/it]

Saved partial generated rows: 18670

 34%|███▍      | 329/962 [37:27<1:09:01,  6.54s/it]

Saved partial generated rows: 18680

 34%|███▍      | 330/962 [37:33<1:08:03,  6.46s/it]

Saved partial generated rows: 18690

 34%|███▍      | 331/962 [37:40<1:08:29,  6.51s/it]

Saved partial generated rows: 18700

 35%|███▍      | 332/962 [37:45<1:05:49,  6.27s/it]

Saved partial generated rows: 18710

 35%|███▍      | 333/962 [37:51<1:04:36,  6.16s/it]

Saved partial generated rows: 18720

 35%|███▍      | 334/962 [37:59<1:10:31,  6.74s/it]

Saved partial generated rows: 18730

 35%|███▍      | 335/962 [38:10<1:22:13,  7.87s/it]

Saved partial generated rows: 18740

 35%|███▍      | 336/962 [38:17<1:19:54,  7.66s/it]

Saved partial generated rows: 18750

 35%|███▌      | 337/962 [38:23<1:16:18,  7.32s/it]

Saved partial generated rows: 18760

 35%|███▌      | 338/962 [38:30<1:14:20,  7.15s/it]

Saved partial generated rows: 18770

 35%|███▌      | 339/962 [38:38<1:15:59,  7.32s/it]

Saved partial generated rows: 18780

 35%|███▌      | 340/962 [38:46<1:18:35,  7.58s/it]

Saved partial generated rows: 18790

 35%|███▌      | 341/962 [38:53<1:15:35,  7.30s/it]

Saved partial generated rows: 18800

 36%|███▌      | 342/962 [38:59<1:12:04,  6.97s/it]

Saved partial generated rows: 18810

 36%|███▌      | 343/962 [39:06<1:13:10,  7.09s/it]

Saved partial generated rows: 18820

 36%|███▌      | 344/962 [39:14<1:13:43,  7.16s/it]

Saved partial generated rows: 18830

 36%|███▌      | 345/962 [39:20<1:11:06,  6.92s/it]

Saved partial generated rows: 18840

 36%|███▌      | 346/962 [39:27<1:11:22,  6.95s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 6.1 seconds before retrying...
Saved partial generated rows: 18850

 36%|███▌      | 347/962 [39:41<1:31:55,  8.97s/it]

Saved partial generated rows: 18860

 36%|███▌      | 348/962 [39:49<1:28:29,  8.65s/it]

Saved partial generated rows: 18870

 36%|███▋      | 349/962 [39:55<1:21:58,  8.02s/it]

Saved partial generated rows: 18880

 36%|███▋      | 350/962 [40:02<1:18:54,  7.74s/it]

Saved partial generated rows: 18890

 36%|███▋      | 351/962 [40:09<1:15:11,  7.38s/it]

Saved partial generated rows: 18900

 37%|███▋      | 352/962 [40:15<1:10:30,  6.93s/it]

Saved partial generated rows: 18910

 37%|███▋      | 353/962 [40:21<1:08:18,  6.73s/it]

Saved partial generated rows: 18920

 37%|███▋      | 354/962 [40:30<1:16:03,  7.51s/it]

Saved partial generated rows: 18930

 37%|███▋      | 355/962 [40:36<1:11:29,  7.07s/it]

Saved partial generated rows: 18940

 37%|███▋      | 356/962 [40:42<1:07:36,  6.69s/it]

Saved partial generated rows: 18950

 37%|███▋      | 357/962 [40:48<1:05:47,  6.52s/it]

Saved partial generated rows: 18960

 37%|███▋      | 358/962 [40:55<1:05:50,  6.54s/it]

Saved partial generated rows: 18970

 37%|███▋      | 359/962 [41:01<1:05:08,  6.48s/it]

Saved partial generated rows: 18980

 37%|███▋      | 360/962 [41:07<1:03:04,  6.29s/it]

Saved partial generated rows: 18990

 38%|███▊      | 361/962 [41:13<1:01:37,  6.15s/it]

Saved partial generated rows: 19000

 38%|███▊      | 362/962 [41:19<1:00:52,  6.09s/it]

Saved partial generated rows: 19010

 38%|███▊      | 363/962 [41:24<59:06,  5.92s/it]

Saved partial generated rows: 19020

 38%|███▊      | 364/962 [41:30<58:02,  5.82s/it]

Saved partial generated rows: 19030

 38%|███▊      | 365/962 [41:40<1:10:44,  7.11s/it]

Saved partial generated rows: 19040

 38%|███▊      | 366/962 [41:46<1:08:24,  6.89s/it]

Saved partial generated rows: 19050

 38%|███▊      | 367/962 [41:53<1:07:26,  6.80s/it]

Saved partial generated rows: 19060

 38%|███▊      | 368/962 [42:02<1:14:43,  7.55s/it]

Saved partial generated rows: 19070

 38%|███▊      | 369/962 [42:12<1:22:03,  8.30s/it]

Saved partial generated rows: 19080

 38%|███▊      | 370/962 [42:20<1:20:58,  8.21s/it]

Saved partial generated rows: 19090

 39%|███▊      | 371/962 [42:28<1:18:22,  7.96s/it]

Saved partial generated rows: 19100

 39%|███▊      | 372/962 [42:34<1:13:22,  7.46s/it]

Saved partial generated rows: 19110

 39%|███▉      | 373/962 [42:40<1:09:45,  7.11s/it]

Saved partial generated rows: 19120

 39%|███▉      | 374/962 [42:47<1:09:16,  7.07s/it]

Saved partial generated rows: 19130

 39%|███▉      | 375/962 [42:54<1:07:38,  6.91s/it]

Saved partial generated rows: 19140

 39%|███▉      | 376/962 [43:00<1:06:33,  6.82s/it]

Saved partial generated rows: 19150

 39%|███▉      | 377/962 [43:08<1:08:34,  7.03s/it]

Saved partial generated rows: 19160

 39%|███▉      | 378/962 [43:15<1:07:04,  6.89s/it]

Saved partial generated rows: 19170

 39%|███▉      | 379/962 [43:21<1:05:30,  6.74s/it]

Saved partial generated rows: 19180

 40%|███▉      | 380/962 [43:27<1:04:25,  6.64s/it]

Saved partial generated rows: 19190

 40%|███▉      | 381/962 [43:33<1:02:43,  6.48s/it]

Saved partial generated rows: 19200

 40%|███▉      | 382/962 [43:40<1:02:22,  6.45s/it]

Saved partial generated rows: 19210

 40%|███▉      | 383/962 [43:45<59:51,  6.20s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 5.9 seconds before retrying...
Saved partial generated rows: 19220

 40%|███▉      | 384/962 [43:59<1:20:01,  8.31s/it]

Saved partial generated rows: 19230

 40%|████      | 385/962 [44:05<1:13:22,  7.63s/it]

Saved partial generated rows: 19240

 40%|████      | 386/962 [44:11<1:08:03,  7.09s/it]

Saved partial generated rows: 19250

 40%|████      | 387/962 [44:16<1:03:46,  6.66s/it]

Saved partial generated rows: 19260

 40%|████      | 388/962 [44:23<1:03:40,  6.66s/it]

Saved partial generated rows: 19270

 40%|████      | 389/962 [44:30<1:05:49,  6.89s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 5.2 seconds before retrying...
Saved partial generated rows: 19280

 41%|████      | 390/962 [44:43<1:20:58,  8.49s/it]

Saved partial generated rows: 19290

 41%|████      | 391/962 [44:48<1:13:12,  7.69s/it]

Saved partial generated rows: 19300

 41%|████      | 392/962 [44:56<1:12:26,  7.63s/it]

Saved partial generated rows: 19310

 41%|████      | 393/962 [45:03<1:11:19,  7.52s/it]

Saved partial generated rows: 19320

 41%|████      | 394/962 [45:09<1:07:34,  7.14s/it]

Saved partial generated rows: 19330

 41%|████      | 395/962 [45:16<1:06:05,  6.99s/it]

Saved partial generated rows: 19340

 41%|████      | 396/962 [45:24<1:10:09,  7.44s/it]

Saved partial generated rows: 19350

 41%|████▏     | 397/962 [45:31<1:06:10,  7.03s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 7.1 seconds before retrying...
Saved partial generated rows: 19360

 41%|████▏     | 398/962 [45:45<1:27:43,  9.33s/it]

Saved partial generated rows: 19370

 41%|████▏     | 399/962 [45:51<1:17:49,  8.29s/it]

Saved partial generated rows: 19380

 42%|████▏     | 400/962 [45:57<1:12:01,  7.69s/it]

Saved partial generated rows: 19390

 42%|████▏     | 401/962 [46:04<1:07:42,  7.24s/it]

Saved partial generated rows: 19400

 42%|████▏     | 402/962 [46:10<1:04:14,  6.88s/it]

Saved partial generated rows: 19410

 42%|████▏     | 403/962 [46:16<1:02:39,  6.73s/it]

Saved partial generated rows: 19420

 42%|████▏     | 404/962 [46:24<1:05:12,  7.01s/it]

Saved partial generated rows: 19430

 42%|████▏     | 405/962 [46:30<1:02:38,  6.75s/it]

Saved partial generated rows: 19440

 42%|████▏     | 406/962 [46:36<1:00:19,  6.51s/it]

Saved partial generated rows: 19450

 42%|████▏     | 407/962 [46:42<59:17,  6.41s/it]

Saved partial generated rows: 19460

 42%|████▏     | 408/962 [46:49<1:01:46,  6.69s/it]

Saved partial generated rows: 19470

 43%|████▎     | 409/962 [46:55<59:35,  6.46s/it]

Saved partial generated rows: 19480

 43%|████▎     | 410/962 [47:03<1:03:24,  6.89s/it]

Saved partial generated rows: 19490

 43%|████▎     | 411/962 [47:10<1:02:37,  6.82s/it]

Saved partial generated rows: 19500

 43%|████▎     | 412/962 [47:16<59:47,  6.52s/it]

Saved partial generated rows: 19510

 43%|████▎     | 413/962 [47:22<58:38,  6.41s/it]

Saved partial generated rows: 19520

 43%|████▎     | 414/962 [47:29<59:35,  6.52s/it]

Saved partial generated rows: 19530

 43%|████▎     | 415/962 [47:36<1:01:09,  6.71s/it]

Saved partial generated rows: 19540

 43%|████▎     | 416/962 [47:42<58:40,  6.45s/it]

Saved partial generated rows: 19550

 43%|████▎     | 417/962 [47:48<57:44,  6.36s/it]

Saved partial generated rows: 19560

 43%|████▎     | 418/962 [47:54<58:19,  6.43s/it]

Saved partial generated rows: 19570

 44%|████▎     | 419/962 [48:01<58:29,  6.46s/it]

Saved partial generated rows: 19580

 44%|████▎     | 420/962 [48:07<56:52,  6.30s/it]

Saved partial generated rows: 19590

 44%|████▍     | 421/962 [48:14<59:23,  6.59s/it]

Saved partial generated rows: 19600

 44%|████▍     | 422/962 [48:19<56:13,  6.25s/it]

Saved partial generated rows: 19610

 44%|████▍     | 423/962 [48:25<54:56,  6.12s/it]

Saved partial generated rows: 19620

 44%|████▍     | 424/962 [48:32<56:01,  6.25s/it]

Saved partial generated rows: 19630

 44%|████▍     | 425/962 [48:39<57:17,  6.40s/it]

Saved partial generated rows: 19640

 44%|████▍     | 426/962 [48:44<55:22,  6.20s/it]

Saved partial generated rows: 19650

 44%|████▍     | 427/962 [48:51<55:24,  6.21s/it]

Saved partial generated rows: 19660

 44%|████▍     | 428/962 [48:58<57:47,  6.49s/it]

Saved partial generated rows: 19670

 45%|████▍     | 429/962 [49:04<57:28,  6.47s/it]

Saved partial generated rows: 19680

 45%|████▍     | 430/962 [49:10<56:23,  6.36s/it]

Saved partial generated rows: 19690

 45%|████▍     | 431/962 [49:17<56:48,  6.42s/it]

Saved partial generated rows: 19700

 45%|████▍     | 432/962 [49:23<57:20,  6.49s/it]

Saved partial generated rows: 19710

 45%|████▌     | 433/962 [49:30<57:23,  6.51s/it]

Saved partial generated rows: 19720

 45%|████▌     | 434/962 [49:36<55:59,  6.36s/it]

Saved partial generated rows: 19730

 45%|████▌     | 435/962 [49:42<55:47,  6.35s/it]

Saved partial generated rows: 19740

 45%|████▌     | 436/962 [49:48<54:42,  6.24s/it]

Saved partial generated rows: 19750

 45%|████▌     | 437/962 [49:54<52:45,  6.03s/it]

Saved partial generated rows: 19760

 46%|████▌     | 438/962 [50:00<53:12,  6.09s/it]

Saved partial generated rows: 19770

 46%|████▌     | 439/962 [50:07<55:07,  6.32s/it]

Saved partial generated rows: 19780

 46%|████▌     | 440/962 [50:14<56:25,  6.49s/it]

Saved partial generated rows: 19790

 46%|████▌     | 441/962 [50:20<54:53,  6.32s/it]

Saved partial generated rows: 19800

 46%|████▌     | 442/962 [50:29<1:02:10,  7.17s/it]

Saved partial generated rows: 19810

 46%|████▌     | 443/962 [50:35<58:43,  6.79s/it]

Saved partial generated rows: 19820

 46%|████▌     | 444/962 [50:42<59:02,  6.84s/it]

Saved partial generated rows: 19830

 46%|████▋     | 445/962 [50:48<58:11,  6.75s/it]

Saved partial generated rows: 19840

 46%|████▋     | 446/962 [50:55<57:03,  6.63s/it]

Saved partial generated rows: 19850

 46%|████▋     | 447/962 [51:01<55:24,  6.46s/it]

Saved partial generated rows: 19860

 47%|████▋     | 448/962 [51:07<55:18,  6.46s/it]

Saved partial generated rows: 19870

 47%|████▋     | 449/962 [51:14<55:58,  6.55s/it]

Saved partial generated rows: 19880

 47%|████▋     | 450/962 [51:23<1:03:12,  7.41s/it]

Saved partial generated rows: 19890

 47%|████▋     | 451/962 [51:30<1:02:29,  7.34s/it]

Saved partial generated rows: 19900

 47%|████▋     | 452/962 [51:37<1:00:03,  7.07s/it]

Saved partial generated rows: 19910

 47%|████▋     | 453/962 [51:44<58:56,  6.95s/it]

Saved partial generated rows: 19920

 47%|████▋     | 454/962 [51:50<56:31,  6.68s/it]

Saved partial generated rows: 19930

 47%|████▋     | 455/962 [51:55<54:01,  6.39s/it]

Saved partial generated rows: 19940

 47%|████▋     | 456/962 [52:05<1:02:02,  7.36s/it]

Saved partial generated rows: 19950

 48%|████▊     | 457/962 [52:11<59:10,  7.03s/it]

Saved partial generated rows: 19960

 48%|████▊     | 458/962 [52:17<56:33,  6.73s/it]

Saved partial generated rows: 19970

 48%|████▊     | 459/962 [52:27<1:03:28,  7.57s/it]

Saved partial generated rows: 19980

 48%|████▊     | 460/962 [52:35<1:05:40,  7.85s/it]

Generation attempt 1/8 failed.
Error: ValueError('Missing row_id(s) in response: [19986]')
Waiting 5.3 seconds before retrying...
Saved partial generated rows: 19990

 48%|████▊     | 461/962 [52:52<1:28:28, 10.60s/it]

Saved partial generated rows: 20000

 48%|████▊     | 462/962 [52:59<1:18:11,  9.38s/it]

Saved partial generated rows: 20010

 48%|████▊     | 463/962 [53:06<1:12:48,  8.75s/it]

Saved partial generated rows: 20020

 48%|████▊     | 464/962 [53:12<1:06:21,  8.00s/it]

Generation attempt 1/8 failed.
Error: ValueError('Missing row_id(s) in response: [20026]')
Waiting 5.4 seconds before retrying...
Saved partial generated rows: 20030

 48%|████▊     | 465/962 [53:31<1:33:11, 11.25s/it]

Saved partial generated rows: 20040

 48%|████▊     | 466/962 [53:37<1:20:04,  9.69s/it]

Saved partial generated rows: 20050

 49%|████▊     | 467/962 [53:44<1:11:54,  8.72s/it]

Saved partial generated rows: 20060

 49%|████▊     | 468/962 [53:50<1:05:39,  7.97s/it]

Saved partial generated rows: 20070

 49%|████▉     | 469/962 [53:58<1:04:33,  7.86s/it]

Saved partial generated rows: 20080

 49%|████▉     | 470/962 [54:07<1:08:16,  8.33s/it]

Saved partial generated rows: 20090

 49%|████▉     | 471/962 [54:13<1:02:16,  7.61s/it]

Saved partial generated rows: 20100

 49%|████▉     | 472/962 [54:19<59:18,  7.26s/it]

Saved partial generated rows: 20110

 49%|████▉     | 473/962 [54:25<55:26,  6.80s/it]

Saved partial generated rows: 20120

 49%|████▉     | 474/962 [54:34<59:58,  7.37s/it]

Saved partial generated rows: 20130

 49%|████▉     | 475/962 [54:41<59:42,  7.36s/it]

Saved partial generated rows: 20140

 49%|████▉     | 476/962 [54:47<57:02,  7.04s/it]

Saved partial generated rows: 20150

 50%|████▉     | 477/962 [54:54<55:29,  6.86s/it]

Saved partial generated rows: 20160

 50%|████▉     | 478/962 [55:00<53:37,  6.65s/it]

Saved partial generated rows: 20170

 50%|████▉     | 479/962 [55:06<52:03,  6.47s/it]

Saved partial generated rows: 20180

 50%|████▉     | 480/962 [55:12<50:13,  6.25s/it]

Saved partial generated rows: 20190

 50%|█████     | 481/962 [55:18<50:48,  6.34s/it]

Saved partial generated rows: 20200

 50%|█████     | 482/962 [55:24<49:14,  6.16s/it]

Saved partial generated rows: 20210

 50%|█████     | 483/962 [55:30<48:52,  6.12s/it]

Saved partial generated rows: 20220

 50%|█████     | 484/962 [55:37<50:18,  6.31s/it]

Saved partial generated rows: 20230

 50%|█████     | 485/962 [55:44<51:06,  6.43s/it]

Saved partial generated rows: 20240

 51%|█████     | 486/962 [55:49<49:29,  6.24s/it]

Saved partial generated rows: 20250

 51%|█████     | 487/962 [55:55<49:08,  6.21s/it]

Saved partial generated rows: 20260

 51%|█████     | 488/962 [56:01<47:55,  6.07s/it]

Saved partial generated rows: 20270

 51%|█████     | 489/962 [56:07<47:46,  6.06s/it]

Saved partial generated rows: 20280

 51%|█████     | 490/962 [56:14<49:47,  6.33s/it]

Saved partial generated rows: 20290

 51%|█████     | 491/962 [56:19<47:05,  6.00s/it]

Saved partial generated rows: 20300

 51%|█████     | 492/962 [56:26<47:05,  6.01s/it]

Saved partial generated rows: 20310

 51%|█████     | 493/962 [56:32<47:41,  6.10s/it]

Saved partial generated rows: 20320

 51%|█████▏    | 494/962 [56:38<47:16,  6.06s/it]

Saved partial generated rows: 20330

 51%|█████▏    | 495/962 [56:43<45:29,  5.85s/it]

Saved partial generated rows: 20340

 52%|█████▏    | 496/962 [56:50<46:48,  6.03s/it]

Saved partial generated rows: 20350

 52%|█████▏    | 497/962 [56:56<47:27,  6.12s/it]

Saved partial generated rows: 20360

 52%|█████▏    | 498/962 [57:02<46:24,  6.00s/it]

Saved partial generated rows: 20370

 52%|█████▏    | 499/962 [57:08<46:40,  6.05s/it]

Saved partial generated rows: 20380

 52%|█████▏    | 500/962 [57:15<50:20,  6.54s/it]

Saved partial generated rows: 20390

 52%|█████▏    | 501/962 [57:22<49:20,  6.42s/it]

Saved partial generated rows: 20400

 52%|█████▏    | 502/962 [57:27<47:52,  6.25s/it]

Saved partial generated rows: 20410

 52%|█████▏    | 503/962 [57:33<46:43,  6.11s/it]

Saved partial generated rows: 20420

 52%|█████▏    | 504/962 [57:40<47:59,  6.29s/it]

Saved partial generated rows: 20430

 52%|█████▏    | 505/962 [57:46<46:25,  6.10s/it]

Saved partial generated rows: 20440

 53%|█████▎    | 506/962 [57:52<46:10,  6.07s/it]

Saved partial generated rows: 20450

 53%|█████▎    | 507/962 [57:59<48:04,  6.34s/it]

Saved partial generated rows: 20460

 53%|█████▎    | 508/962 [58:05<47:32,  6.28s/it]

Saved partial generated rows: 20470

 53%|█████▎    | 509/962 [58:11<47:34,  6.30s/it]

Saved partial generated rows: 20480

 53%|█████▎    | 510/962 [58:17<46:11,  6.13s/it]

Saved partial generated rows: 20490

 53%|█████▎    | 511/962 [58:23<46:04,  6.13s/it]

Saved partial generated rows: 20500

 53%|█████▎    | 512/962 [58:29<46:02,  6.14s/it]

Saved partial generated rows: 20510

 53%|█████▎    | 513/962 [58:36<47:06,  6.29s/it]

Saved partial generated rows: 20520

 53%|█████▎    | 514/962 [58:43<48:16,  6.46s/it]

Saved partial generated rows: 20530

 54%|█████▎    | 515/962 [58:50<49:44,  6.68s/it]

Saved partial generated rows: 20540

 54%|█████▎    | 516/962 [58:57<50:29,  6.79s/it]

Saved partial generated rows: 20550

 54%|█████▎    | 517/962 [59:04<50:45,  6.84s/it]

Saved partial generated rows: 20560

 54%|█████▍    | 518/962 [59:10<48:24,  6.54s/it]

Saved partial generated rows: 20570

 54%|█████▍    | 519/962 [59:16<48:19,  6.55s/it]

Saved partial generated rows: 20580

 54%|█████▍    | 520/962 [59:23<48:55,  6.64s/it]

Saved partial generated rows: 20590

 54%|█████▍    | 521/962 [59:29<47:55,  6.52s/it]

Saved partial generated rows: 20600

 54%|█████▍    | 522/962 [59:36<47:41,  6.50s/it]

Saved partial generated rows: 20610

 54%|█████▍    | 523/962 [59:42<46:06,  6.30s/it]

Saved partial generated rows: 20620

 54%|█████▍    | 524/962 [59:49<47:29,  6.51s/it]

Saved partial generated rows: 20630

 55%|█████▍    | 525/962 [59:54<45:38,  6.27s/it]

Saved partial generated rows: 20640

 55%|█████▍    | 526/962 [1:00:00<44:10,  6.08s/it]

Saved partial generated rows: 20650

 55%|█████▍    | 527/962 [1:00:07<45:58,  6.34s/it]

Saved partial generated rows: 20660

 55%|█████▍    | 528/962 [1:00:12<43:25,  6.00s/it]

Saved partial generated rows: 20670

 55%|█████▍    | 529/962 [1:00:18<43:40,  6.05s/it]

Saved partial generated rows: 20680

 55%|█████▌    | 530/962 [1:00:25<45:31,  6.32s/it]

Saved partial generated rows: 20690

 55%|█████▌    | 531/962 [1:00:31<43:43,  6.09s/it]

Saved partial generated rows: 20700

 55%|█████▌    | 532/962 [1:00:37<44:26,  6.20s/it]

Saved partial generated rows: 20710

 55%|█████▌    | 533/962 [1:00:44<45:23,  6.35s/it]

Saved partial generated rows: 20720

 56%|█████▌    | 534/962 [1:00:50<44:17,  6.21s/it]

Saved partial generated rows: 20730

 56%|█████▌    | 535/962 [1:00:57<46:01,  6.47s/it]

Saved partial generated rows: 20740

 56%|█████▌    | 536/962 [1:01:03<46:06,  6.49s/it]

Saved partial generated rows: 20750

 56%|█████▌    | 537/962 [1:01:09<44:29,  6.28s/it]

Saved partial generated rows: 20760

 56%|█████▌    | 538/962 [1:01:16<44:51,  6.35s/it]

Saved partial generated rows: 20770

 56%|█████▌    | 539/962 [1:01:22<44:58,  6.38s/it]

Saved partial generated rows: 20780

 56%|█████▌    | 540/962 [1:01:29<45:52,  6.52s/it]

Saved partial generated rows: 20790

 56%|█████▌    | 541/962 [1:01:36<46:03,  6.56s/it]

Saved partial generated rows: 20800

 56%|█████▋    | 542/962 [1:01:43<47:12,  6.74s/it]

Saved partial generated rows: 20810

 56%|█████▋    | 543/962 [1:01:50<48:11,  6.90s/it]

Saved partial generated rows: 20820

 57%|█████▋    | 544/962 [1:01:56<46:05,  6.62s/it]

Saved partial generated rows: 20830

 57%|█████▋    | 545/962 [1:02:02<44:45,  6.44s/it]

Saved partial generated rows: 20840

 57%|█████▋    | 546/962 [1:02:08<44:06,  6.36s/it]

Saved partial generated rows: 20850

 57%|█████▋    | 547/962 [1:02:15<43:42,  6.32s/it]

Saved partial generated rows: 20860

 57%|█████▋    | 548/962 [1:02:22<46:37,  6.76s/it]

Saved partial generated rows: 20870

 57%|█████▋    | 549/962 [1:02:28<43:46,  6.36s/it]

Saved partial generated rows: 20880

 57%|█████▋    | 550/962 [1:02:35<45:58,  6.69s/it]

Saved partial generated rows: 20890

 57%|█████▋    | 551/962 [1:02:43<48:16,  7.05s/it]

Saved partial generated rows: 20900

 57%|█████▋    | 552/962 [1:02:49<46:07,  6.75s/it]

Saved partial generated rows: 20910

 57%|█████▋    | 553/962 [1:02:56<46:00,  6.75s/it]

Saved partial generated rows: 20920

 58%|█████▊    | 554/962 [1:03:02<44:40,  6.57s/it]

Saved partial generated rows: 20930

 58%|█████▊    | 555/962 [1:03:09<45:34,  6.72s/it]

Saved partial generated rows: 20940

 58%|█████▊    | 556/962 [1:03:16<44:55,  6.64s/it]

Saved partial generated rows: 20950

 58%|█████▊    | 557/962 [1:03:22<43:48,  6.49s/it]

Saved partial generated rows: 20960

 58%|█████▊    | 558/962 [1:03:28<43:40,  6.49s/it]

Saved partial generated rows: 20970

 58%|█████▊    | 559/962 [1:03:34<42:32,  6.33s/it]

Saved partial generated rows: 20980

 58%|█████▊    | 560/962 [1:03:41<43:09,  6.44s/it]

Saved partial generated rows: 20990

 58%|█████▊    | 561/962 [1:03:47<41:38,  6.23s/it]

Saved partial generated rows: 21000

 58%|█████▊    | 562/962 [1:03:52<40:19,  6.05s/it]

Saved partial generated rows: 21010

 59%|█████▊    | 563/962 [1:04:00<43:25,  6.53s/it]

Saved partial generated rows: 21020

 59%|█████▊    | 564/962 [1:04:05<41:23,  6.24s/it]

Saved partial generated rows: 21030

 59%|█████▊    | 565/962 [1:04:12<41:05,  6.21s/it]

Saved partial generated rows: 21040

 59%|█████▉    | 566/962 [1:04:17<40:03,  6.07s/it]

Saved partial generated rows: 21050

 59%|█████▉    | 567/962 [1:04:24<40:42,  6.18s/it]

Saved partial generated rows: 21060

 59%|█████▉    | 568/962 [1:04:29<39:23,  6.00s/it]

Saved partial generated rows: 21070

 59%|█████▉    | 569/962 [1:04:35<38:32,  5.89s/it]

Saved partial generated rows: 21080

 59%|█████▉    | 570/962 [1:04:44<45:07,  6.91s/it]

Saved partial generated rows: 21090

 59%|█████▉    | 571/962 [1:04:50<43:43,  6.71s/it]

Saved partial generated rows: 21100

 59%|█████▉    | 572/962 [1:04:58<45:30,  7.00s/it]

Saved partial generated rows: 21110

 60%|█████▉    | 573/962 [1:05:06<47:34,  7.34s/it]

Saved partial generated rows: 21120

 60%|█████▉    | 574/962 [1:05:13<46:15,  7.15s/it]

Saved partial generated rows: 21130

 60%|█████▉    | 575/962 [1:05:19<43:00,  6.67s/it]

Saved partial generated rows: 21140

 60%|█████▉    | 576/962 [1:05:25<41:52,  6.51s/it]

Saved partial generated rows: 21150

 60%|█████▉    | 577/962 [1:05:30<40:17,  6.28s/it]

Saved partial generated rows: 21160

 60%|██████    | 578/962 [1:05:36<38:08,  5.96s/it]

Saved partial generated rows: 21170

 60%|██████    | 579/962 [1:05:43<40:45,  6.38s/it]

Saved partial generated rows: 21180

 60%|██████    | 580/962 [1:05:50<41:43,  6.55s/it]

Saved partial generated rows: 21190

 60%|██████    | 581/962 [1:05:55<39:18,  6.19s/it]

Saved partial generated rows: 21200

 60%|██████    | 582/962 [1:06:01<38:55,  6.15s/it]

Saved partial generated rows: 21210

 61%|██████    | 583/962 [1:06:08<39:12,  6.21s/it]

Saved partial generated rows: 21220

 61%|██████    | 584/962 [1:06:15<41:17,  6.55s/it]

Saved partial generated rows: 21230

 61%|██████    | 585/962 [1:06:21<40:48,  6.50s/it]

Saved partial generated rows: 21240

 61%|██████    | 586/962 [1:06:27<38:40,  6.17s/it]

Saved partial generated rows: 21250

 61%|██████    | 587/962 [1:06:34<40:16,  6.44s/it]

Saved partial generated rows: 21260

 61%|██████    | 588/962 [1:06:40<40:10,  6.44s/it]

Saved partial generated rows: 21270

 61%|██████    | 589/962 [1:06:46<38:44,  6.23s/it]

Saved partial generated rows: 21280

 61%|██████▏   | 590/962 [1:06:52<38:40,  6.24s/it]

Saved partial generated rows: 21290

 61%|██████▏   | 591/962 [1:06:59<38:34,  6.24s/it]

Saved partial generated rows: 21300

 62%|██████▏   | 592/962 [1:07:04<37:32,  6.09s/it]

Saved partial generated rows: 21310

 62%|██████▏   | 593/962 [1:07:10<37:37,  6.12s/it]

Saved partial generated rows: 21320

 62%|██████▏   | 594/962 [1:07:17<38:16,  6.24s/it]

Saved partial generated rows: 21330

 62%|██████▏   | 595/962 [1:07:29<49:26,  8.08s/it]

Saved partial generated rows: 21340

 62%|██████▏   | 596/962 [1:07:35<45:22,  7.44s/it]

Saved partial generated rows: 21350

 62%|██████▏   | 597/962 [1:07:42<44:01,  7.24s/it]

Saved partial generated rows: 21360

 62%|██████▏   | 598/962 [1:07:48<41:18,  6.81s/it]

Saved partial generated rows: 21370

 62%|██████▏   | 599/962 [1:07:54<39:53,  6.59s/it]

Saved partial generated rows: 21380

 62%|██████▏   | 600/962 [1:08:01<39:51,  6.61s/it]

Saved partial generated rows: 21390

 62%|██████▏   | 601/962 [1:08:07<39:49,  6.62s/it]

Saved partial generated rows: 21400

 63%|██████▎   | 602/962 [1:08:13<38:29,  6.42s/it]

Saved partial generated rows: 21410

 63%|██████▎   | 603/962 [1:08:19<37:21,  6.24s/it]

Saved partial generated rows: 21420

 63%|██████▎   | 604/962 [1:08:26<38:10,  6.40s/it]

Saved partial generated rows: 21430

 63%|██████▎   | 605/962 [1:08:32<36:52,  6.20s/it]

Saved partial generated rows: 21440

 63%|██████▎   | 606/962 [1:08:39<38:19,  6.46s/it]

Saved partial generated rows: 21450

 63%|██████▎   | 607/962 [1:08:45<38:22,  6.49s/it]

Saved partial generated rows: 21460

 63%|██████▎   | 608/962 [1:08:51<36:52,  6.25s/it]

Saved partial generated rows: 21470

 63%|██████▎   | 609/962 [1:08:57<36:50,  6.26s/it]

Saved partial generated rows: 21480

 63%|██████▎   | 610/962 [1:09:03<35:37,  6.07s/it]

Saved partial generated rows: 21490

 64%|██████▎   | 611/962 [1:09:09<35:27,  6.06s/it]

Saved partial generated rows: 21500

 64%|██████▎   | 612/962 [1:09:16<37:29,  6.43s/it]

Saved partial generated rows: 21510

 64%|██████▎   | 613/962 [1:09:22<35:48,  6.16s/it]

Saved partial generated rows: 21520

 64%|██████▍   | 614/962 [1:09:28<36:02,  6.22s/it]

Saved partial generated rows: 21530

 64%|██████▍   | 615/962 [1:09:35<37:14,  6.44s/it]

Saved partial generated rows: 21540

 64%|██████▍   | 616/962 [1:09:42<38:34,  6.69s/it]

Saved partial generated rows: 21550

 64%|██████▍   | 617/962 [1:09:49<38:34,  6.71s/it]

Saved partial generated rows: 21560

 64%|██████▍   | 618/962 [1:09:55<36:26,  6.36s/it]

Saved partial generated rows: 21570

 64%|██████▍   | 619/962 [1:10:01<36:08,  6.32s/it]

Saved partial generated rows: 21580

 64%|██████▍   | 620/962 [1:10:08<37:08,  6.52s/it]

Saved partial generated rows: 21590

 65%|██████▍   | 621/962 [1:10:15<37:47,  6.65s/it]

Saved partial generated rows: 21600

 65%|██████▍   | 622/962 [1:10:21<36:17,  6.41s/it]

Saved partial generated rows: 21610

 65%|██████▍   | 623/962 [1:10:27<36:58,  6.54s/it]

Saved partial generated rows: 21620

 65%|██████▍   | 624/962 [1:10:33<35:53,  6.37s/it]

Saved partial generated rows: 21630

 65%|██████▍   | 625/962 [1:10:39<34:11,  6.09s/it]

Saved partial generated rows: 21640

 65%|██████▌   | 626/962 [1:10:45<33:58,  6.07s/it]

Saved partial generated rows: 21650

 65%|██████▌   | 627/962 [1:10:51<34:51,  6.24s/it]

Saved partial generated rows: 21660

 65%|██████▌   | 628/962 [1:10:57<33:23,  6.00s/it]

Saved partial generated rows: 21670

 65%|██████▌   | 629/962 [1:11:03<34:12,  6.16s/it]

Saved partial generated rows: 21680

 65%|██████▌   | 630/962 [1:11:10<34:55,  6.31s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 6.0 seconds before retrying...
Saved partial generated rows: 21690

 66%|██████▌   | 631/962 [1:11:24<46:44,  8.47s/it]

Saved partial generated rows: 21700

 66%|██████▌   | 632/962 [1:11:29<42:14,  7.68s/it]

Saved partial generated rows: 21710

 66%|██████▌   | 633/962 [1:11:36<39:55,  7.28s/it]

Saved partial generated rows: 21720

 66%|██████▌   | 634/962 [1:11:41<36:56,  6.76s/it]

Generation attempt 1/8 failed.
Error: ValueError('Missing row_id(s) in response: [21723]')
Waiting 7.9 seconds before retrying...
Saved partial generated rows: 21730

 66%|██████▌   | 635/962 [1:11:59<55:24, 10.17s/it]

Saved partial generated rows: 21740

 66%|██████▌   | 636/962 [1:12:06<48:54,  9.00s/it]

Saved partial generated rows: 21750

 66%|██████▌   | 637/962 [1:12:12<44:53,  8.29s/it]

Saved partial generated rows: 21760

 66%|██████▋   | 638/962 [1:12:18<40:46,  7.55s/it]

Saved partial generated rows: 21770

 66%|██████▋   | 639/962 [1:12:24<37:33,  6.98s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 5.5 seconds before retrying...
Saved partial generated rows: 21780

 67%|██████▋   | 640/962 [1:12:36<46:29,  8.66s/it]

Saved partial generated rows: 21790

 67%|██████▋   | 641/962 [1:12:43<42:37,  7.97s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 5.2 seconds before retrying...
Saved partial generated rows: 21800

 67%|██████▋   | 642/962 [1:12:56<50:13,  9.42s/it]

Saved partial generated rows: 21810

 67%|██████▋   | 643/962 [1:13:01<43:42,  8.22s/it]

Saved partial generated rows: 21820

 67%|██████▋   | 644/962 [1:13:07<39:46,  7.51s/it]

Saved partial generated rows: 21830

 67%|██████▋   | 645/962 [1:13:14<39:16,  7.43s/it]

Saved partial generated rows: 21840

 67%|██████▋   | 646/962 [1:13:20<37:06,  7.05s/it]

Saved partial generated rows: 21850

 67%|██████▋   | 647/962 [1:13:26<34:36,  6.59s/it]

Saved partial generated rows: 21860

 67%|██████▋   | 648/962 [1:13:32<34:36,  6.61s/it]

Saved partial generated rows: 21870

 67%|██████▋   | 649/962 [1:13:40<35:30,  6.81s/it]

Saved partial generated rows: 21880

 68%|██████▊   | 650/962 [1:13:46<35:20,  6.80s/it]

Saved partial generated rows: 21890

 68%|██████▊   | 651/962 [1:13:52<34:02,  6.57s/it]

Saved partial generated rows: 21900

 68%|██████▊   | 652/962 [1:13:59<34:22,  6.65s/it]

Saved partial generated rows: 21910

 68%|██████▊   | 653/962 [1:14:06<34:26,  6.69s/it]

Saved partial generated rows: 21920

 68%|██████▊   | 654/962 [1:14:11<31:52,  6.21s/it]

Saved partial generated rows: 21930

 68%|██████▊   | 655/962 [1:14:18<33:08,  6.48s/it]

Saved partial generated rows: 21940

 68%|██████▊   | 656/962 [1:14:24<31:34,  6.19s/it]

Saved partial generated rows: 21950

 68%|██████▊   | 657/962 [1:14:31<33:16,  6.55s/it]

Saved partial generated rows: 21960

 68%|██████▊   | 658/962 [1:14:38<33:00,  6.52s/it]

Saved partial generated rows: 21970

 69%|██████▊   | 659/962 [1:14:44<32:11,  6.38s/it]

Saved partial generated rows: 21980

 69%|██████▊   | 660/962 [1:14:50<31:35,  6.28s/it]

Saved partial generated rows: 21990

 69%|██████▊   | 661/962 [1:14:56<31:53,  6.36s/it]

Saved partial generated rows: 22000

 69%|██████▉   | 662/962 [1:15:03<31:46,  6.36s/it]

Saved partial generated rows: 22010

 69%|██████▉   | 663/962 [1:15:09<31:49,  6.39s/it]

Saved partial generated rows: 22020

 69%|██████▉   | 664/962 [1:15:15<30:44,  6.19s/it]

Saved partial generated rows: 22030

 69%|██████▉   | 665/962 [1:15:21<31:19,  6.33s/it]

Saved partial generated rows: 22040

 69%|██████▉   | 666/962 [1:15:28<32:10,  6.52s/it]

Saved partial generated rows: 22050

 69%|██████▉   | 667/962 [1:15:34<31:12,  6.35s/it]

Saved partial generated rows: 22060

 69%|██████▉   | 668/962 [1:15:40<30:11,  6.16s/it]

Saved partial generated rows: 22070

 70%|██████▉   | 669/962 [1:15:46<29:38,  6.07s/it]

Saved partial generated rows: 22080

 70%|██████▉   | 670/962 [1:15:51<28:08,  5.78s/it]

Saved partial generated rows: 22090

 70%|██████▉   | 671/962 [1:15:56<27:12,  5.61s/it]

Saved partial generated rows: 22100

 70%|██████▉   | 672/962 [1:16:02<27:00,  5.59s/it]

Saved partial generated rows: 22110

 70%|██████▉   | 673/962 [1:16:08<27:43,  5.76s/it]

Saved partial generated rows: 22120

 70%|███████   | 674/962 [1:16:14<28:27,  5.93s/it]

Saved partial generated rows: 22130

 70%|███████   | 675/962 [1:16:20<27:30,  5.75s/it]

Saved partial generated rows: 22140

 70%|███████   | 676/962 [1:16:25<26:57,  5.66s/it]

Saved partial generated rows: 22150

 70%|███████   | 677/962 [1:16:31<27:16,  5.74s/it]

Saved partial generated rows: 22160

 70%|███████   | 678/962 [1:16:37<27:09,  5.74s/it]

Saved partial generated rows: 22170

 71%|███████   | 679/962 [1:16:42<27:03,  5.74s/it]

Saved partial generated rows: 22180

 71%|███████   | 680/962 [1:16:48<26:05,  5.55s/it]

Saved partial generated rows: 22190

 71%|███████   | 681/962 [1:16:53<25:58,  5.55s/it]

Saved partial generated rows: 22200

 71%|███████   | 682/962 [1:16:59<25:59,  5.57s/it]

Saved partial generated rows: 22210

 71%|███████   | 683/962 [1:17:06<27:33,  5.93s/it]

Saved partial generated rows: 22220

 71%|███████   | 684/962 [1:17:11<27:03,  5.84s/it]

Saved partial generated rows: 22230

 71%|███████   | 685/962 [1:17:17<27:05,  5.87s/it]

Saved partial generated rows: 22240

 71%|███████▏  | 686/962 [1:17:23<27:22,  5.95s/it]

Saved partial generated rows: 22250

 71%|███████▏  | 687/962 [1:17:29<26:58,  5.89s/it]

Saved partial generated rows: 22260

 72%|███████▏  | 688/962 [1:17:36<28:23,  6.22s/it]

Saved partial generated rows: 22270

 72%|███████▏  | 689/962 [1:17:42<28:17,  6.22s/it]

Saved partial generated rows: 22280

 72%|███████▏  | 690/962 [1:17:48<27:15,  6.01s/it]

Saved partial generated rows: 22290

 72%|███████▏  | 691/962 [1:17:54<27:35,  6.11s/it]

Saved partial generated rows: 22300

 72%|███████▏  | 692/962 [1:18:00<26:52,  5.97s/it]

Saved partial generated rows: 22310

 72%|███████▏  | 693/962 [1:18:05<26:10,  5.84s/it]

Saved partial generated rows: 22320

 72%|███████▏  | 694/962 [1:18:12<27:26,  6.14s/it]

Saved partial generated rows: 22330

 72%|███████▏  | 695/962 [1:18:17<26:19,  5.91s/it]

Saved partial generated rows: 22340

 72%|███████▏  | 696/962 [1:18:24<27:08,  6.12s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 7.1 seconds before retrying...
Saved partial generated rows: 22350

 72%|███████▏  | 697/962 [1:18:40<40:34,  9.19s/it]

Saved partial generated rows: 22360

 73%|███████▎  | 698/962 [1:18:47<36:27,  8.29s/it]

Saved partial generated rows: 22370

 73%|███████▎  | 699/962 [1:18:54<35:39,  8.14s/it]

Saved partial generated rows: 22380

 73%|███████▎  | 700/962 [1:19:01<32:59,  7.56s/it]

Saved partial generated rows: 22390

 73%|███████▎  | 701/962 [1:19:07<30:54,  7.11s/it]

Saved partial generated rows: 22400

 73%|███████▎  | 702/962 [1:19:12<29:02,  6.70s/it]

Saved partial generated rows: 22410

 73%|███████▎  | 703/962 [1:19:21<31:07,  7.21s/it]

Saved partial generated rows: 22420

 73%|███████▎  | 704/962 [1:19:26<28:58,  6.74s/it]

Saved partial generated rows: 22430

 73%|███████▎  | 705/962 [1:19:32<27:42,  6.47s/it]

Saved partial generated rows: 22440

 73%|███████▎  | 706/962 [1:19:38<26:39,  6.25s/it]

Saved partial generated rows: 22450

 73%|███████▎  | 707/962 [1:19:44<26:01,  6.12s/it]

Saved partial generated rows: 22460

 74%|███████▎  | 708/962 [1:19:50<25:41,  6.07s/it]

Saved partial generated rows: 22470

 74%|███████▎  | 709/962 [1:19:56<26:17,  6.23s/it]

Saved partial generated rows: 22480

 74%|███████▍  | 710/962 [1:20:02<25:36,  6.10s/it]

Saved partial generated rows: 22490

 74%|███████▍  | 711/962 [1:20:09<26:12,  6.26s/it]

Saved partial generated rows: 22500

 74%|███████▍  | 712/962 [1:20:15<26:04,  6.26s/it]

Saved partial generated rows: 22510

 74%|███████▍  | 713/962 [1:20:22<26:15,  6.33s/it]

Saved partial generated rows: 22520

 74%|███████▍  | 714/962 [1:20:27<25:22,  6.14s/it]

Saved partial generated rows: 22530

 74%|███████▍  | 715/962 [1:20:35<27:09,  6.60s/it]

Saved partial generated rows: 22540

 74%|███████▍  | 716/962 [1:20:41<26:30,  6.46s/it]

Saved partial generated rows: 22550

 75%|███████▍  | 717/962 [1:20:48<26:45,  6.55s/it]

Saved partial generated rows: 22560

 75%|███████▍  | 718/962 [1:20:54<25:59,  6.39s/it]

Saved partial generated rows: 22570

 75%|███████▍  | 719/962 [1:20:59<24:36,  6.08s/it]

Saved partial generated rows: 22580

 75%|███████▍  | 720/962 [1:21:05<24:15,  6.01s/it]

Saved partial generated rows: 22590

 75%|███████▍  | 721/962 [1:21:12<24:54,  6.20s/it]

Saved partial generated rows: 22600

 75%|███████▌  | 722/962 [1:21:18<25:13,  6.31s/it]

Saved partial generated rows: 22610

 75%|███████▌  | 723/962 [1:21:24<24:41,  6.20s/it]

Saved partial generated rows: 22620

 75%|███████▌  | 724/962 [1:21:31<25:14,  6.37s/it]

Saved partial generated rows: 22630

 75%|███████▌  | 725/962 [1:21:37<24:38,  6.24s/it]

Saved partial generated rows: 22640

 75%|███████▌  | 726/962 [1:21:43<24:47,  6.30s/it]

Saved partial generated rows: 22650

 76%|███████▌  | 727/962 [1:21:49<24:15,  6.19s/it]

Saved partial generated rows: 22660

 76%|███████▌  | 728/962 [1:21:55<24:05,  6.18s/it]

Saved partial generated rows: 22670

 76%|███████▌  | 729/962 [1:22:01<23:25,  6.03s/it]

Saved partial generated rows: 22680

 76%|███████▌  | 730/962 [1:22:08<24:06,  6.23s/it]

Saved partial generated rows: 22690

 76%|███████▌  | 731/962 [1:22:16<25:39,  6.67s/it]

Saved partial generated rows: 22700

 76%|███████▌  | 732/962 [1:22:22<24:57,  6.51s/it]

Saved partial generated rows: 22710

 76%|███████▌  | 733/962 [1:22:27<23:43,  6.22s/it]

Saved partial generated rows: 22720

 76%|███████▋  | 734/962 [1:22:33<22:50,  6.01s/it]

Saved partial generated rows: 22730

 76%|███████▋  | 735/962 [1:22:39<22:32,  5.96s/it]

Saved partial generated rows: 22740

 77%|███████▋  | 736/962 [1:22:44<22:03,  5.86s/it]

Saved partial generated rows: 22750

 77%|███████▋  | 737/962 [1:22:50<21:56,  5.85s/it]

Saved partial generated rows: 22760

 77%|███████▋  | 738/962 [1:22:57<23:12,  6.22s/it]

Saved partial generated rows: 22770

 77%|███████▋  | 739/962 [1:23:03<22:44,  6.12s/it]

Saved partial generated rows: 22780

 77%|███████▋  | 740/962 [1:23:10<23:24,  6.33s/it]

Saved partial generated rows: 22790

 77%|███████▋  | 741/962 [1:23:16<22:59,  6.24s/it]

Saved partial generated rows: 22800

 77%|███████▋  | 742/962 [1:23:22<22:26,  6.12s/it]

Saved partial generated rows: 22810

 77%|███████▋  | 743/962 [1:23:31<25:30,  6.99s/it]

Saved partial generated rows: 22820

 77%|███████▋  | 744/962 [1:23:36<24:01,  6.61s/it]

Saved partial generated rows: 22830

 77%|███████▋  | 745/962 [1:23:42<23:01,  6.37s/it]

Saved partial generated rows: 22840

 78%|███████▊  | 746/962 [1:23:48<22:29,  6.25s/it]

Saved partial generated rows: 22850

 78%|███████▊  | 747/962 [1:23:55<22:43,  6.34s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 6.5 seconds before retrying...
Saved partial generated rows: 22860

 78%|███████▊  | 748/962 [1:24:09<30:51,  8.65s/it]

Saved partial generated rows: 22870

 78%|███████▊  | 749/962 [1:24:14<27:24,  7.72s/it]

Saved partial generated rows: 22880

 78%|███████▊  | 750/962 [1:24:20<25:34,  7.24s/it]

Saved partial generated rows: 22890

 78%|███████▊  | 751/962 [1:24:27<24:31,  6.98s/it]

Saved partial generated rows: 22900

 78%|███████▊  | 752/962 [1:24:33<23:05,  6.60s/it]

Saved partial generated rows: 22910

 78%|███████▊  | 753/962 [1:24:38<21:58,  6.31s/it]

Saved partial generated rows: 22920

 78%|███████▊  | 754/962 [1:24:45<22:52,  6.60s/it]

Saved partial generated rows: 22930

 78%|███████▊  | 755/962 [1:24:51<21:39,  6.28s/it]

Saved partial generated rows: 22940

 79%|███████▊  | 756/962 [1:24:56<20:40,  6.02s/it]

Saved partial generated rows: 22950

 79%|███████▊  | 757/962 [1:25:02<20:04,  5.87s/it]

Saved partial generated rows: 22960

 79%|███████▉  | 758/962 [1:25:09<20:47,  6.12s/it]

Saved partial generated rows: 22970

 79%|███████▉  | 759/962 [1:25:15<20:42,  6.12s/it]

Saved partial generated rows: 22980

 79%|███████▉  | 760/962 [1:25:22<22:10,  6.59s/it]

Saved partial generated rows: 22990

 79%|███████▉  | 761/962 [1:25:30<22:57,  6.85s/it]

Saved partial generated rows: 23000

 79%|███████▉  | 762/962 [1:25:35<21:25,  6.43s/it]

Saved partial generated rows: 23010

 79%|███████▉  | 763/962 [1:25:41<20:19,  6.13s/it]

Saved partial generated rows: 23020

 79%|███████▉  | 764/962 [1:25:48<20:56,  6.35s/it]

Saved partial generated rows: 23030

 80%|███████▉  | 765/962 [1:25:53<20:01,  6.10s/it]

Saved partial generated rows: 23040

 80%|███████▉  | 766/962 [1:25:59<19:46,  6.05s/it]

Saved partial generated rows: 23050

 80%|███████▉  | 767/962 [1:26:05<19:27,  5.99s/it]

Saved partial generated rows: 23060

 80%|███████▉  | 768/962 [1:26:12<20:24,  6.31s/it]

Saved partial generated rows: 23070

 80%|███████▉  | 769/962 [1:26:18<19:50,  6.17s/it]

Saved partial generated rows: 23080

 80%|████████  | 770/962 [1:26:23<19:15,  6.02s/it]

Saved partial generated rows: 23090

 80%|████████  | 771/962 [1:26:30<19:26,  6.11s/it]

Saved partial generated rows: 23100

 80%|████████  | 772/962 [1:26:36<19:16,  6.09s/it]

Saved partial generated rows: 23110

 80%|████████  | 773/962 [1:26:42<19:31,  6.20s/it]

Saved partial generated rows: 23120

 80%|████████  | 774/962 [1:26:51<21:28,  6.85s/it]

Saved partial generated rows: 23130

 81%|████████  | 775/962 [1:26:57<20:48,  6.67s/it]

Saved partial generated rows: 23140

 81%|████████  | 776/962 [1:27:03<20:23,  6.58s/it]

Saved partial generated rows: 23150

 81%|████████  | 777/962 [1:27:10<20:21,  6.60s/it]

Saved partial generated rows: 23160

 81%|████████  | 778/962 [1:27:15<19:15,  6.28s/it]

Saved partial generated rows: 23170

 81%|████████  | 779/962 [1:27:21<18:33,  6.09s/it]

Saved partial generated rows: 23180

 81%|████████  | 780/962 [1:27:28<19:03,  6.28s/it]

Saved partial generated rows: 23190

 81%|████████  | 781/962 [1:27:36<20:41,  6.86s/it]

Saved partial generated rows: 23200

 81%|████████▏ | 782/962 [1:27:42<19:50,  6.61s/it]

Saved partial generated rows: 23210

 81%|████████▏ | 783/962 [1:27:49<20:02,  6.72s/it]

Saved partial generated rows: 23220

 81%|████████▏ | 784/962 [1:27:55<19:03,  6.42s/it]

Saved partial generated rows: 23230

 82%|████████▏ | 785/962 [1:28:05<22:16,  7.55s/it]

Saved partial generated rows: 23240

 82%|████████▏ | 786/962 [1:28:11<20:41,  7.05s/it]

Saved partial generated rows: 23250

 82%|████████▏ | 787/962 [1:28:17<19:41,  6.75s/it]

Saved partial generated rows: 23260

 82%|████████▏ | 788/962 [1:28:23<18:47,  6.48s/it]

Saved partial generated rows: 23270

 82%|████████▏ | 789/962 [1:28:29<18:33,  6.44s/it]

Saved partial generated rows: 23280

 82%|████████▏ | 790/962 [1:28:36<18:28,  6.44s/it]

Saved partial generated rows: 23290

 82%|████████▏ | 791/962 [1:28:42<18:43,  6.57s/it]

Saved partial generated rows: 23300

 82%|████████▏ | 792/962 [1:28:49<18:30,  6.53s/it]

Saved partial generated rows: 23310

 82%|████████▏ | 793/962 [1:28:55<18:21,  6.52s/it]

Saved partial generated rows: 23320

 83%|████████▎ | 794/962 [1:29:01<17:20,  6.19s/it]

Saved partial generated rows: 23330

 83%|████████▎ | 795/962 [1:29:06<16:23,  5.89s/it]

Saved partial generated rows: 23340

 83%|████████▎ | 796/962 [1:29:15<19:03,  6.89s/it]

Saved partial generated rows: 23350

 83%|████████▎ | 797/962 [1:29:24<20:46,  7.55s/it]

Saved partial generated rows: 23360

 83%|████████▎ | 798/962 [1:29:31<19:54,  7.29s/it]

Saved partial generated rows: 23370

 83%|████████▎ | 799/962 [1:29:39<20:09,  7.42s/it]

Saved partial generated rows: 23380

 83%|████████▎ | 800/962 [1:29:45<19:12,  7.11s/it]

Saved partial generated rows: 23390

 83%|████████▎ | 801/962 [1:29:52<18:52,  7.03s/it]

Saved partial generated rows: 23400

 83%|████████▎ | 802/962 [1:29:58<18:08,  6.80s/it]

Saved partial generated rows: 23410

 83%|████████▎ | 803/962 [1:30:05<18:08,  6.85s/it]

Saved partial generated rows: 23420

 84%|████████▎ | 804/962 [1:30:11<17:33,  6.67s/it]

Saved partial generated rows: 23430

 84%|████████▎ | 805/962 [1:30:18<17:31,  6.70s/it]

Saved partial generated rows: 23440

 84%|████████▍ | 806/962 [1:30:24<16:34,  6.38s/it]

Saved partial generated rows: 23450

 84%|████████▍ | 807/962 [1:30:31<16:51,  6.52s/it]

Saved partial generated rows: 23460

 84%|████████▍ | 808/962 [1:30:37<16:27,  6.41s/it]

Saved partial generated rows: 23470

 84%|████████▍ | 809/962 [1:30:43<16:13,  6.36s/it]

Saved partial generated rows: 23480

 84%|████████▍ | 810/962 [1:30:49<15:28,  6.11s/it]

Saved partial generated rows: 23490

 84%|████████▍ | 811/962 [1:30:54<15:05,  6.00s/it]

Saved partial generated rows: 23500

 84%|████████▍ | 812/962 [1:31:05<18:10,  7.27s/it]

Saved partial generated rows: 23510

 85%|████████▍ | 813/962 [1:31:13<18:49,  7.58s/it]

Saved partial generated rows: 23520

 85%|████████▍ | 814/962 [1:31:19<17:33,  7.12s/it]

Saved partial generated rows: 23530

 85%|████████▍ | 815/962 [1:31:25<16:34,  6.76s/it]

Saved partial generated rows: 23540

 85%|████████▍ | 816/962 [1:31:32<16:45,  6.88s/it]

Saved partial generated rows: 23550

 85%|████████▍ | 817/962 [1:31:38<16:13,  6.72s/it]

Saved partial generated rows: 23560

 85%|████████▌ | 818/962 [1:31:45<15:46,  6.57s/it]

Saved partial generated rows: 23570

 85%|████████▌ | 819/962 [1:31:52<15:58,  6.70s/it]

Saved partial generated rows: 23580

 85%|████████▌ | 820/962 [1:32:01<18:00,  7.61s/it]

Saved partial generated rows: 23590

 85%|████████▌ | 821/962 [1:32:08<17:12,  7.32s/it]

Saved partial generated rows: 23600

 85%|████████▌ | 822/962 [1:32:14<15:54,  6.82s/it]

Saved partial generated rows: 23610

 86%|████████▌ | 823/962 [1:32:22<16:53,  7.29s/it]

Saved partial generated rows: 23620

 86%|████████▌ | 824/962 [1:32:28<15:46,  6.86s/it]

Saved partial generated rows: 23630

 86%|████████▌ | 825/962 [1:32:38<18:09,  7.96s/it]

Saved partial generated rows: 23640

 86%|████████▌ | 826/962 [1:32:45<17:09,  7.57s/it]

Saved partial generated rows: 23650

 86%|████████▌ | 827/962 [1:32:53<17:02,  7.57s/it]

Saved partial generated rows: 23660

 86%|████████▌ | 828/962 [1:32:59<16:13,  7.27s/it]

Saved partial generated rows: 23670

 86%|████████▌ | 829/962 [1:33:05<15:21,  6.93s/it]

Saved partial generated rows: 23680

 86%|████████▋ | 830/962 [1:33:12<14:51,  6.76s/it]

Saved partial generated rows: 23690

 86%|████████▋ | 831/962 [1:33:18<14:45,  6.76s/it]

Saved partial generated rows: 23700

 86%|████████▋ | 832/962 [1:33:24<13:46,  6.36s/it]

Saved partial generated rows: 23710

 87%|████████▋ | 833/962 [1:33:31<13:55,  6.48s/it]

Saved partial generated rows: 23720

 87%|████████▋ | 834/962 [1:33:39<15:02,  7.05s/it]

Saved partial generated rows: 23730

 87%|████████▋ | 835/962 [1:33:45<14:32,  6.87s/it]

Saved partial generated rows: 23740

 87%|████████▋ | 836/962 [1:33:51<13:50,  6.59s/it]

Saved partial generated rows: 23750

 87%|████████▋ | 837/962 [1:33:57<13:08,  6.31s/it]

Saved partial generated rows: 23760

 87%|████████▋ | 838/962 [1:34:03<12:36,  6.10s/it]

Saved partial generated rows: 23770

 87%|████████▋ | 839/962 [1:34:09<12:24,  6.05s/it]

Saved partial generated rows: 23780

 87%|████████▋ | 840/962 [1:34:15<12:27,  6.13s/it]

Saved partial generated rows: 23790

 87%|████████▋ | 841/962 [1:34:22<12:42,  6.30s/it]

Saved partial generated rows: 23800

 88%|████████▊ | 842/962 [1:34:28<12:41,  6.35s/it]

Saved partial generated rows: 23810

 88%|████████▊ | 843/962 [1:34:42<16:53,  8.51s/it]

Saved partial generated rows: 23820

 88%|████████▊ | 844/962 [1:34:49<15:55,  8.10s/it]

Saved partial generated rows: 23830

 88%|████████▊ | 845/962 [1:34:55<14:41,  7.54s/it]

Saved partial generated rows: 23840

 88%|████████▊ | 846/962 [1:35:00<13:24,  6.94s/it]

Saved partial generated rows: 23850

 88%|████████▊ | 847/962 [1:35:07<12:50,  6.70s/it]

Saved partial generated rows: 23860

 88%|████████▊ | 848/962 [1:35:12<12:14,  6.44s/it]

Saved partial generated rows: 23870

 88%|████████▊ | 849/962 [1:35:18<11:40,  6.20s/it]

Saved partial generated rows: 23880

 88%|████████▊ | 850/962 [1:35:23<10:59,  5.89s/it]

Saved partial generated rows: 23890

 88%|████████▊ | 851/962 [1:35:29<10:50,  5.86s/it]

Saved partial generated rows: 23900

 89%|████████▊ | 852/962 [1:35:37<11:51,  6.47s/it]

Saved partial generated rows: 23910

 89%|████████▊ | 853/962 [1:35:43<11:27,  6.31s/it]

Saved partial generated rows: 23920

 89%|████████▉ | 854/962 [1:35:49<11:29,  6.38s/it]

Saved partial generated rows: 23930

 89%|████████▉ | 855/962 [1:35:56<11:28,  6.43s/it]

Saved partial generated rows: 23940

 89%|████████▉ | 856/962 [1:36:03<11:25,  6.47s/it]

Saved partial generated rows: 23950

 89%|████████▉ | 857/962 [1:36:10<11:43,  6.70s/it]

Saved partial generated rows: 23960

 89%|████████▉ | 858/962 [1:36:15<11:04,  6.39s/it]

Saved partial generated rows: 23970

 89%|████████▉ | 859/962 [1:36:25<12:50,  7.49s/it]

Saved partial generated rows: 23980

 89%|████████▉ | 860/962 [1:36:31<11:40,  6.87s/it]

Saved partial generated rows: 23990

 90%|████████▉ | 861/962 [1:36:37<10:59,  6.53s/it]

Saved partial generated rows: 24000

 90%|████████▉ | 862/962 [1:36:44<11:05,  6.65s/it]

Saved partial generated rows: 24010

 90%|████████▉ | 863/962 [1:36:49<10:29,  6.36s/it]

Saved partial generated rows: 24020

 90%|████████▉ | 864/962 [1:36:56<10:28,  6.41s/it]

Saved partial generated rows: 24030

 90%|████████▉ | 865/962 [1:37:02<10:11,  6.30s/it]

Saved partial generated rows: 24040

 90%|█████████ | 866/962 [1:37:08<10:14,  6.41s/it]

Saved partial generated rows: 24050

 90%|█████████ | 867/962 [1:37:15<10:18,  6.51s/it]

Saved partial generated rows: 24060

 90%|█████████ | 868/962 [1:37:22<10:19,  6.59s/it]

Saved partial generated rows: 24070

 90%|█████████ | 869/962 [1:37:28<09:51,  6.36s/it]

Saved partial generated rows: 24080

 90%|█████████ | 870/962 [1:37:34<09:39,  6.30s/it]

Generation attempt 1/8 failed.
Error: ValueError('Missing row_id(s) in response: [24085]')
Waiting 6.3 seconds before retrying...
Saved partial generated rows: 24090

 91%|█████████ | 871/962 [1:37:51<14:23,  9.49s/it]

Saved partial generated rows: 24100

 91%|█████████ | 872/962 [1:37:56<12:23,  8.26s/it]

Saved partial generated rows: 24110

 91%|█████████ | 873/962 [1:38:02<11:04,  7.47s/it]

Saved partial generated rows: 24120

 91%|█████████ | 874/962 [1:38:08<10:27,  7.13s/it]

Saved partial generated rows: 24130

 91%|█████████ | 875/962 [1:38:15<10:13,  7.05s/it]

Saved partial generated rows: 24140

 91%|█████████ | 876/962 [1:38:22<09:53,  6.90s/it]

Saved partial generated rows: 24150

 91%|█████████ | 877/962 [1:38:27<09:14,  6.52s/it]

Saved partial generated rows: 24160

 91%|█████████▏| 878/962 [1:38:33<08:58,  6.41s/it]

Saved partial generated rows: 24170

 91%|█████████▏| 879/962 [1:38:40<08:47,  6.36s/it]

Saved partial generated rows: 24180

 91%|█████████▏| 880/962 [1:38:46<08:36,  6.30s/it]

Saved partial generated rows: 24190

 92%|█████████▏| 881/962 [1:38:52<08:26,  6.25s/it]

Saved partial generated rows: 24200

 92%|█████████▏| 882/962 [1:38:58<08:17,  6.22s/it]

Saved partial generated rows: 24210

 92%|█████████▏| 883/962 [1:39:04<08:11,  6.22s/it]

Saved partial generated rows: 24220

 92%|█████████▏| 884/962 [1:39:11<08:10,  6.29s/it]

Saved partial generated rows: 24230

 92%|█████████▏| 885/962 [1:39:16<07:47,  6.07s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 7.7 seconds before retrying...
Saved partial generated rows: 24240

 92%|█████████▏| 886/962 [1:39:31<10:56,  8.63s/it]

Saved partial generated rows: 24250

 92%|█████████▏| 887/962 [1:39:37<09:44,  7.80s/it]

Saved partial generated rows: 24260

 92%|█████████▏| 888/962 [1:39:44<09:20,  7.58s/it]

Saved partial generated rows: 24270

 92%|█████████▏| 889/962 [1:39:50<08:30,  6.99s/it]

Saved partial generated rows: 24280

 93%|█████████▎| 890/962 [1:39:56<08:16,  6.90s/it]

Saved partial generated rows: 24290

 93%|█████████▎| 891/962 [1:40:02<07:55,  6.70s/it]

Saved partial generated rows: 24300

 93%|█████████▎| 892/962 [1:40:09<07:51,  6.73s/it]

Saved partial generated rows: 24310

 93%|█████████▎| 893/962 [1:40:15<07:14,  6.30s/it]

Saved partial generated rows: 24320

 93%|█████████▎| 894/962 [1:40:20<06:52,  6.06s/it]

Saved partial generated rows: 24330

 93%|█████████▎| 895/962 [1:40:25<06:31,  5.84s/it]

Saved partial generated rows: 24340

 93%|█████████▎| 896/962 [1:40:31<06:15,  5.69s/it]

Generation attempt 1/8 failed.
Error: ServerError("503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}")
Waiting 7.0 seconds before retrying...
Saved partial generated rows: 24350

 93%|█████████▎| 897/962 [1:40:46<09:14,  8.53s/it]

Saved partial generated rows: 24360

 93%|█████████▎| 898/962 [1:40:52<08:12,  7.69s/it]

Saved partial generated rows: 24370

 93%|█████████▎| 899/962 [1:40:57<07:25,  7.07s/it]

Saved partial generated rows: 24380

 94%|█████████▎| 900/962 [1:41:03<06:59,  6.76s/it]

Saved partial generated rows: 24390

 94%|█████████▎| 901/962 [1:41:09<06:41,  6.58s/it]

Saved partial generated rows: 24400

 94%|█████████▍| 902/962 [1:41:15<06:10,  6.18s/it]

Saved partial generated rows: 24410

 94%|█████████▍| 903/962 [1:41:21<06:07,  6.22s/it]

Saved partial generated rows: 24420

 94%|█████████▍| 904/962 [1:41:28<06:06,  6.32s/it]

Saved partial generated rows: 24430

 94%|█████████▍| 905/962 [1:41:34<06:00,  6.33s/it]

Saved partial generated rows: 24440

 94%|█████████▍| 906/962 [1:41:40<05:58,  6.39s/it]

Saved partial generated rows: 24450

 94%|█████████▍| 907/962 [1:41:47<05:46,  6.29s/it]

Saved partial generated rows: 24460

 94%|█████████▍| 908/962 [1:41:52<05:34,  6.19s/it]

Saved partial generated rows: 24470

 94%|█████████▍| 909/962 [1:41:58<05:25,  6.14s/it]

Saved partial generated rows: 24480

 95%|█████████▍| 910/962 [1:42:05<05:24,  6.25s/it]

Saved partial generated rows: 24490

 95%|█████████▍| 911/962 [1:42:11<05:08,  6.05s/it]

Saved partial generated rows: 24500

 95%|█████████▍| 912/962 [1:42:17<05:00,  6.02s/it]

Saved partial generated rows: 24510

 95%|█████████▍| 913/962 [1:42:22<04:47,  5.87s/it]

Saved partial generated rows: 24520

 95%|█████████▌| 914/962 [1:42:29<04:59,  6.23s/it]

Saved partial generated rows: 24530

 95%|█████████▌| 915/962 [1:42:34<04:38,  5.93s/it]

Saved partial generated rows: 24540

 95%|█████████▌| 916/962 [1:42:40<04:31,  5.90s/it]

Saved partial generated rows: 24550

 95%|█████████▌| 917/962 [1:42:46<04:28,  5.97s/it]

Saved partial generated rows: 24560

 95%|█████████▌| 918/962 [1:42:52<04:18,  5.87s/it]

Saved partial generated rows: 24570

 96%|█████████▌| 919/962 [1:42:59<04:26,  6.20s/it]

Saved partial generated rows: 24580

 96%|█████████▌| 920/962 [1:43:04<04:11,  5.99s/it]

Saved partial generated rows: 24590

 96%|█████████▌| 921/962 [1:43:11<04:12,  6.15s/it]

Saved partial generated rows: 24600

 96%|█████████▌| 922/962 [1:43:17<04:10,  6.26s/it]

Saved partial generated rows: 24610

 96%|█████████▌| 923/962 [1:43:23<03:55,  6.04s/it]

Saved partial generated rows: 24620

 96%|█████████▌| 924/962 [1:43:29<03:47,  5.98s/it]

Saved partial generated rows: 24630

 96%|█████████▌| 925/962 [1:43:35<03:47,  6.15s/it]

Saved partial generated rows: 24640

 96%|█████████▋| 926/962 [1:43:41<03:39,  6.09s/it]

Saved partial generated rows: 24650

 96%|█████████▋| 927/962 [1:43:48<03:39,  6.26s/it]

Saved partial generated rows: 24660

 96%|█████████▋| 928/962 [1:43:53<03:24,  6.01s/it]

Saved partial generated rows: 24670

 97%|█████████▋| 929/962 [1:43:59<03:13,  5.87s/it]

Saved partial generated rows: 24680

 97%|█████████▋| 930/962 [1:44:06<03:20,  6.26s/it]

Saved partial generated rows: 24690

 97%|█████████▋| 931/962 [1:44:12<03:14,  6.28s/it]

Saved partial generated rows: 24700

 97%|█████████▋| 932/962 [1:44:18<03:02,  6.09s/it]

Saved partial generated rows: 24710

 97%|█████████▋| 933/962 [1:44:25<03:02,  6.29s/it]

Saved partial generated rows: 24720

 97%|█████████▋| 934/962 [1:44:31<02:58,  6.37s/it]

Saved partial generated rows: 24730

 97%|█████████▋| 935/962 [1:44:38<02:51,  6.36s/it]

Saved partial generated rows: 24740

 97%|█████████▋| 936/962 [1:44:44<02:43,  6.30s/it]

Saved partial generated rows: 24750

 97%|█████████▋| 937/962 [1:44:50<02:33,  6.16s/it]

Saved partial generated rows: 24760

 98%|█████████▊| 938/962 [1:44:57<02:34,  6.45s/it]

Saved partial generated rows: 24770

 98%|█████████▊| 939/962 [1:45:02<02:21,  6.15s/it]

Saved partial generated rows: 24780

 98%|█████████▊| 940/962 [1:45:09<02:19,  6.33s/it]

Saved partial generated rows: 24790

 98%|█████████▊| 941/962 [1:45:15<02:08,  6.12s/it]

Saved partial generated rows: 24800

 98%|█████████▊| 942/962 [1:45:20<01:57,  5.86s/it]

Saved partial generated rows: 24810

 98%|█████████▊| 943/962 [1:45:25<01:48,  5.73s/it]

Saved partial generated rows: 24820

 98%|█████████▊| 944/962 [1:45:31<01:41,  5.66s/it]

Saved partial generated rows: 24830

 98%|█████████▊| 945/962 [1:45:37<01:40,  5.90s/it]

Saved partial generated rows: 24840

 98%|█████████▊| 946/962 [1:45:44<01:39,  6.22s/it]

Saved partial generated rows: 24850

 98%|█████████▊| 947/962 [1:45:50<01:31,  6.07s/it]

Saved partial generated rows: 24860

 99%|█████████▊| 948/962 [1:45:57<01:27,  6.28s/it]

Saved partial generated rows: 24870

 99%|█████████▊| 949/962 [1:46:02<01:17,  5.99s/it]

Saved partial generated rows: 24880

 99%|█████████▉| 950/962 [1:46:09<01:14,  6.22s/it]

Saved partial generated rows: 24890

 99%|█████████▉| 951/962 [1:46:15<01:06,  6.08s/it]

Saved partial generated rows: 24900

 99%|█████████▉| 952/962 [1:46:20<00:57,  5.79s/it]

Saved partial generated rows: 24910

 99%|█████████▉| 953/962 [1:46:26<00:53,  5.89s/it]

Saved partial generated rows: 24920

 99%|█████████▉| 954/962 [1:46:32<00:47,  5.94s/it]

Saved partial generated rows: 24930

 99%|█████████▉| 955/962 [1:46:38<00:41,  5.92s/it]

Saved partial generated rows: 24940

 99%|█████████▉| 956/962 [1:46:44<00:36,  6.01s/it]

Saved partial generated rows: 24950

 99%|█████████▉| 957/962 [1:46:50<00:30,  6.14s/it]

Saved partial generated rows: 24960

100%|█████████▉| 958/962 [1:46:56<00:24,  6.11s/it]

Saved partial generated rows: 24970

100%|█████████▉| 959/962 [1:47:02<00:17,  5.97s/it]

Saved partial generated rows: 24980

100%|█████████▉| 960/962 [1:47:10<00:12,  6.48s/it]

Saved partial generated rows: 24990

100%|█████████▉| 961/962 [1:47:16<00:06,  6.45s/it]

Saved partial generated rows: 25000

100%|██████████| 962/962 [1:47:23<00:00,  6.70s/it]

Generated rows: 25000

,row_id,gen_alpha,semantic_preservation_score,notes
0,0,Setting goals is key when you're gaming compet...,5,The suggestion about setting goals in competit...
1,1,What's the appeal of playing those super spook...,4,The question about enjoying scary games is rep...
2,2,You should get outside more instead of staying...,5,The advice to engage in outdoor activities is ...
3,3,"Follow the game rules, or it's over.",4,The suggestion to respect game rules is transl...
4,4,Maybe step away from gaming for a bit so you d...,5,The advice to take a break from gaming to prev...

No failed batches.

In [12]:
# =============================================================================
# 10. CHECK COMPLETENESS
# =============================================================================
expected_ids = set(src_df["row_id"].astype(int).tolist())

if generated_df.empty:
    generated_ids = set()
else:
    generated_ids = set(generated_df["row_id"].astype(int).tolist())

missing_ids = sorted(expected_ids - generated_ids)

print("Expected rows:", len(expected_ids))
print("Generated rows:", len(generated_ids))
print("Missing rows:", len(missing_ids))

if missing_ids:
    print("First 50 missing row_ids:")
    print(missing_ids[:50])
    print("\nRerun the generation cell later. Resume logic will only process missing rows.")
else:
    print("All rows generated successfully.")

Expected rows: 25000
Generated rows: 25000
Missing rows: 0
All rows generated successfully.

In [13]:
# =============================================================================
# 11. MERGE SOURCE + GENERATED TARGETS
# =============================================================================
if generated_df.empty:
    raise ValueError("No generated rows found. Run generation first.")

translation_df = src_df.merge(generated_df, on="row_id", how="inner")

# Rename row_id to id
translation_df = translation_df.rename(columns={"row_id": "id"})

# Final column order
translation_df = translation_df[
    [
        "id",
        "topic",
        "boomer_style",
        "gen_alpha_style",
        "sentence_type",
        "boomer",
        "gen_alpha",
        "semantic_preservation_score",
        "notes",
    ]
].copy()

# Clean
for col in ["boomer", "gen_alpha", "topic", "boomer_style", "gen_alpha_style", "sentence_type", "notes"]:
    translation_df[col] = translation_df[col].fillna("").astype(str).str.strip()

translation_df["semantic_preservation_score"] = pd.to_numeric(
    translation_df["semantic_preservation_score"],
    errors="coerce"
).fillna(4).astype(int)

translation_df = translation_df[
    (translation_df["boomer"] != "") &
    (translation_df["gen_alpha"] != "")
].copy()

translation_df = translation_df.drop_duplicates(
    subset=["boomer", "gen_alpha"]
).reset_index(drop=True)

translation_df.to_csv(FINAL_OUTPUT_CSV, index=False)

print("Final generated dataset shape:", translation_df.shape)
print("Saved to:", FINAL_OUTPUT_CSV)

display(translation_df.head(20))

Final generated dataset shape: (25000, 9)
Saved to: /Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation/output/generated_25000_gemini25_flashlite_prompt_final.csv

,id,topic,boomer_style,gen_alpha_style,sentence_type,boomer,gen_alpha,semantic_preservation_score,notes
0,0,gaming and hobbies,full lecture mode,main character vibes,requests or suggestions,It’s important to set goals when gaming compet...,Setting goals is key when you're gaming compet...,5,The suggestion about setting goals in competit...
1,1,gaming and hobbies,confused by technology,delulu and delusional optimism,requests or suggestions,How can you enjoy playing those scary games?,What's the appeal of playing those super spook...,4,The question about enjoying scary games is rep...
2,2,gaming and hobbies,unsolicited advice-giver,NPC brainrot,requests or suggestions,You could benefit from some outdoor activities...,You should get outside more instead of staying...,5,The advice to engage in outdoor activities is ...
3,3,gaming and hobbies,full lecture mode,villain arc mentality,requests or suggestions,Respect the rules of each game you play.,"Follow the game rules, or it's over.",4,The suggestion to respect game rules is transl...
4,4,gaming and hobbies,unsolicited advice-giver,NPC brainrot,requests or suggestions,You might want to take a break from gaming bef...,Maybe step away from gaming for a bit so you d...,5,The advice to take a break from gaming to prev...
5,5,gaming and hobbies,overly literal and pedantic,deadpan sarcastic,requests or suggestions,It's important to have a backup plan aside fro...,Having a backup plan that isn't just gaming is...,5,The suggestion for an alternative plan to gami...
6,6,gaming and hobbies,full lecture mode,villain arc mentality,requests or suggestions,Practice regularly to improve your skills in y...,Grind consistently to level up your skills in ...,5,The advice on practicing regularly is translat...
7,7,gaming and hobbies,overly literal and pedantic,delulu and delusional optimism,requests or suggestions,I think you should take a break from gaming to...,Consider taking a gaming break to reset your b...,5,The suggestion to take a gaming break for ment...
8,8,gaming and hobbies,overly polite to the point of awkward,ironic hype,requests or suggestions,Perhaps you could take on a leadership role wi...,You could totally lead your gaming crew.,5,The suggestion to take a leadership role in a ...
9,9,gaming and hobbies,full lecture mode,delulu and delusional optimism,requests or suggestions,Dedicate time to learning about coding or game...,Spend time learning how to code or make games.,5,The suggestion to learn about coding or game d...
10,10,gaming and hobbies,full lecture mode,villain arc mentality,requests or suggestions,Consider the impact of gaming violence on your...,Thinking about violent games can mess with you...,4,The suggestion to consider the impact of gamin...
11,11,gaming and hobbies,overly literal and pedantic,delulu and delusional optimism,requests or suggestions,You ought to appreciate the benefits of physic...,It's a good idea to get into physical hobbies ...,5,The advice to appreciate physical hobbies is p...
12,12,gaming and hobbies,using outdated idioms,extremely overdramatic,requests or suggestions,You might find painting therapeutic.,You could find painting to be pretty chill.,5,The suggestion that painting might be therapeu...
13,13,gaming and hobbies,overly polite to the point of awkward,ironic hype,requests or suggestions,Might it benefit you to review your favorite g...,Maybe you could check out your favorite games ...,5,The polite suggestion to critically review gam...
14,14,gaming and hobbies,nostalgic for the good old days,deadpan sarcastic,requests or suggestions,It’s good to socialize in the real world too.,Hanging out with people IRL is also pretty imp...,5,The sentiment about socializing in the real wo...
15,15,gaming and hobbies,full lecture mode,chronically online,requests or suggestions,You should be open to constructive criticism f...,It's good to be open to what your friends say ...,5,The advice to be open to constructive criticis...
16,16,gaming and hobbies,full lecture mode,delulu and delusional optimism,requests or suggestions,You could benefit from collaborating with othe...,Teaming up with others on gaming projects coul...,5,The suggestion to collaborate on gaming projec...
17,17,gaming and hobbies,overly literal and pedantic,delulu and delusional optimism,requests or suggestions,You might find more discipline through structu...,Having a more structured routine could help yo...,5,The advice that structured activities can lead...
18,18,gaming and hobbies,unsolicited advice-giver,NPC brainrot,requests or suggestions,Consider organizing your game time to make roo...,Think about planning your gaming time so you h...,5,The suggestion to organize game time is rephra...
19,19,gaming and hobbies,overly literal and pedantic,delulu and delusional optimism,requests or suggestions,Why is it so hard for you to enjoy the outdoors?,Why is being outside so hard for you?,5,The question about difficulty enjoying the out...

In [17]:
# =============================================================================
# 12. QUALITY CHECK SAMPLES
# =============================================================================
sample_n = min(30, len(translation_df))
sample_df = translation_df.sample(sample_n, random_state=42)

for _, row in sample_df.iterrows():
    print("=" * 100)
    print("ID:", row["id"])
    print("Topic:", row["topic"])
    print("Sentence type:", row["sentence_type"])
    print("Boomer style:", row["boomer_style"])
    print("Target style:", row["gen_alpha_style"])
    print("\nBoomer:")
    print(row["boomer"])
    print("\nGenerated Gen Alpha:")
    print(row["gen_alpha"])
    print("\nScore:", row["semantic_preservation_score"])
    print("Notes:", row["notes"])

====================================================================================================
ID: 6868
Topic: mental health and feelings
Sentence type: questions
Boomer style: overly polite to the point of awkward
Target style: extremely overdramatic

Boomer:
Would it help to take a moment to reflect on your thoughts?

Generated Gen Alpha:
Could taking a sec to think about your thoughts help?

Score: 5
Notes: Translates the polite suggestion to reflect into a more casual, question format.
====================================================================================================
ID: 24016
Topic: gaming and hobbies
Sentence type: compliments or praise
Boomer style: completely out of touch with youth culture
Target style: unhinged chaos energy

Boomer:
I admire your ability to focus on your interests.

Generated Gen Alpha:
It's cool seeing you lock in on the stuff you're into.

Score: 5
Notes: The original sentence praises focus on interests. The rewritten sentence uses casual, informal language to express admiration.
====================================================================================================
ID: 9668
Topic: family and home
Sentence type: requests or suggestions
Boomer style: worried and concerned parent
Target style: deadpan sarcastic

Boomer:
You should really be more responsible with your money.

Generated Gen Alpha:
Your money management is, let's just say, a choice.

Score: 5
Notes: The suggestion to be more responsible with money is rephrased using sarcastic Gen Alpha phrasing.
====================================================================================================
ID: 13640
Topic: family and home
Sentence type: observations or statements
Boomer style: catastrophizing and dramatic
Target style: delulu and delusional optimism

Boomer:
You can't just throw caution to the wind.

Generated Gen Alpha:
No need to go full send without thinking it through.

Score: 5
Notes: Preserves the meaning of not being reckless.
====================================================================================================
ID: 14018
Topic: school and studying
Sentence type: requests or suggestions
Boomer style: confused by technology
Target style: ironic hype

Boomer:
It’s important to ask questions when you’re confused.

Generated Gen Alpha:
It's pretty important to ask questions when you're confused.

Score: 5
Notes: The advice to ask questions when confused is preserved directly.
====================================================================================================
ID: 7488
Topic: health and medicine
Sentence type: observations or statements
Boomer style: passive-aggressive
Target style: deadpan sarcastic

Boomer:
It’s not good to ignore your pain.

Generated Gen Alpha:
Don't just ignore your pain, that's not the move.

Score: 5
Notes: The warning about ignoring pain is preserved with casual phrasing.
====================================================================================================
ID: 5804
Topic: relationships and dating
Sentence type: questions
Boomer style: using outdated idioms
Target style: rizz-coded smooth talker

Boomer:
Have you ever tried to change for the person you love?

Generated Gen Alpha:
Did you ever try to change for someone you liked?

Score: 5
Notes: Maintains the question about whether the person has attempted to change for a loved one.
====================================================================================================
ID: 12909
Topic: pop culture and entertainment
Sentence type: questions
Boomer style: overly polite to the point of awkward
Target style: low effort minimal energy

Boomer:
Would you be so kind as to recommend a film for me to watch?

Generated Gen Alpha:
Got any movie recs?

Score: 5
Notes: The polite request for a film recommendation is translated into a brief, common way of asking for suggestions.
====================================================================================================
ID: 3386
Topic: politics and news
Sentence type: compliments or praise
Boomer style: worried and concerned parent
Target style: rizz-coded smooth talker

Boomer:
It's nice to see youth taking political action.

Generated Gen Alpha:
It's awesome seeing young people actually care about politics.

Score: 5
Notes: The observation about youth political action is rephrased casually.
====================================================================================================
ID: 9567
Topic: politics and news
Sentence type: exclamations or reactions
Boomer style: formal and slightly stiff
Target style: unhinged chaos energy

Boomer:
We must prioritize national security.

Generated Gen Alpha:
We gotta protect the country's safety, like, seriously.

Score: 5
Notes: The boomer sentence is a formal statement prioritizing national security. The Gen Alpha translation uses casual phrasing like 'gotta' and 'like, seriously' to convey the same urgent priority for safety.
====================================================================================================
ID: 21423
Topic: politics and news
Sentence type: complaints or frustrations
Boomer style: full lecture mode
Target style: unhinged chaos energy

Boomer:
Political ignorance is harmful to society.

Generated Gen Alpha:
Being clueless about politics messes up society, no lie.

Score: 5
Notes: The serious warning about political ignorance is maintained and expressed in a more casual, internet-native way.
====================================================================================================
ID: 3503
Topic: relationships and dating
Sentence type: complaints or frustrations
Boomer style: confused by technology
Target style: extremely overdramatic

Boomer:
Why are you changing your relationship status so often?

Generated Gen Alpha:
Why are you always updating your relationship status like, constantly?

Score: 5
Notes: Preserves the question about frequent relationship status changes, using casual phrasing and 'like'.
====================================================================================================
ID: 6657
Topic: weather and environment
Sentence type: exclamations or reactions
Boomer style: using outdated idioms
Target style: villain arc mentality

Boomer:
The humidity is off the charts today!

Generated Gen Alpha:
The humidity is insane today!

Score: 5
Notes: The exclamation about high humidity is translated into common Gen Alpha phrasing that expresses the same intensity.
====================================================================================================
ID: 19192
Topic: sports and fitness
Sentence type: complaints or frustrations
Boomer style: formal and slightly stiff
Target style: delulu and delusional optimism

Boomer:
Your lack of focus in training is unacceptable.

Generated Gen Alpha:
Your training focus is kinda sus, gotta lock in.

Score: 5
Notes: The complaint about lack of focus is rephrased using casual internet slang that maintains the original meaning.
====================================================================================================
ID: 2518
Topic: weather and environment
Sentence type: requests or suggestions
Boomer style: passive-aggressive
Target style: doomer and nihilistic

Boomer:
Make sure to wear sunscreen; you don't want to get burned.

Generated Gen Alpha:
wear sunscreen, or you'll regret it, like, forever.

Score: 4
Notes: The warning to wear sunscreen is maintained, with the 'doomer and nihilistic' tone coming through in the exaggerated consequence of regret, and the mild use of 'like'.
====================================================================================================
ID: 13361
Topic: fashion and style
Sentence type: commands or instructions
Boomer style: overly polite to the point of awkward
Target style: deadpan sarcastic

Boomer:
You should avoid wearing overly casual attire.

Generated Gen Alpha:
Don't wear super casual outfits, that's kinda cringe.

Score: 5
Notes: Rewrites the advice to avoid casual attire into more modern, informal language.
====================================================================================================
ID: 21135
Topic: fashion and style
Sentence type: observations or statements
Boomer style: confused by technology
Target style: low effort minimal energy

Boomer:
I don't see how you can wear socks with sandals.

Generated Gen Alpha:
Wearing socks with sandals is a choice, I guess.

Score: 4
Notes: The confusion about socks with sandals is conveyed with a slightly more informal and questioning tone, preserving the core idea.
====================================================================================================
ID: 21080
Topic: pop culture and entertainment
Sentence type: requests or suggestions
Boomer style: nostalgic for the good old days
Target style: extremely overdramatic

Boomer:
I remember when movie theaters were cheap and packed with people.

Generated Gen Alpha:
I miss when movie theaters were cheap and everyone went.

Score: 5
Notes: The nostalgic sentiment about movie theaters is preserved with casual language.
====================================================================================================
ID: 6492
Topic: weather and environment
Sentence type: exclamations or reactions
Boomer style: nostalgic for the good old days
Target style: villain arc mentality

Boomer:
The rivers were crystal clear and inviting.

Generated Gen Alpha:
Back in the day, the rivers were so clean.

Score: 5
Notes: The nostalgic statement about clear rivers is rephrased in a casual, relatable way for Gen Alpha.
====================================================================================================
ID: 6891
Topic: mental health and feelings
Sentence type: questions
Boomer style: passive-aggressive
Target style: NPC brainrot

Boomer:
Are you really taking care of yourself?

Generated Gen Alpha:
Are you even real right now?

Score: 5
Notes: The passive-aggressive question about self-care is transformed into a question about authenticity, fitting the 'NPC brainrot' style.
====================================================================================================
ID: 7752
Topic: fashion and style
Sentence type: compliments or praise
Boomer style: confused by technology
Target style: main character vibes

Boomer:
You have a knack for choosing colors that pop.

Generated Gen Alpha:
You're the main character of this whole mess, and your colors are loud.

Score: 4
Notes: Translates 'pop' to 'loud' which has a similar energetic connotation in this context, and reinforces the 'main character' vibe.
====================================================================================================
ID: 8614
Topic: school and studying
Sentence type: compliments or praise
Boomer style: nostalgic for the good old days
Target style: NPC brainrot

Boomer:
Having a good study environment is important.

Generated Gen Alpha:
A decent study spot is key.

Score: 5
Notes: Simplifies the statement about the importance of a study environment into a more direct Gen Alpha expression.
====================================================================================================
ID: 6649
Topic: weather and environment
Sentence type: exclamations or reactions
Boomer style: using outdated idioms
Target style: villain arc mentality

Boomer:
You can feel the energy in the air!

Generated Gen Alpha:
You can literally feel the energy shifting, it's wild.

Score: 4
Notes: The idiom is translated into a more direct, less metaphorical statement about the feeling in the air.
====================================================================================================
ID: 2227
Topic: weather and environment
Sentence type: requests or suggestions
Boomer style: passive-aggressive
Target style: delulu and delusional optimism

Boomer:
I can't believe you're planning a picnic in this weather.

Generated Gen Alpha:
No way you're having a picnic in this weather?

Score: 4
Notes: The original sentence implies disbelief and perhaps disapproval. This translation captures the disbelief but loses some of the passive-aggressive tone by being more direct.
====================================================================================================
ID: 12060
Topic: politics and news
Sentence type: commands or instructions
Boomer style: using outdated idioms
Target style: chronically online

Boomer:
Don't take everything at face value from the news.

Generated Gen Alpha:
Don't just believe everything the news is pushing.

Score: 5
Notes: The command to not take news at face value is preserved with casual language.
====================================================================================================
ID: 19122
Topic: sports and fitness
Sentence type: complaints or frustrations
Boomer style: overly polite to the point of awkward
Target style: rizz-coded smooth talker

Boomer:
It’s essential to hydrate properly during workouts.

Generated Gen Alpha:
Gotta stay hydrated when you're getting your sweat on.

Score: 5
Notes: The essential advice about hydration during workouts is preserved with natural, informal Gen Alpha phrasing.
====================================================================================================
ID: 9622
Topic: family and home
Sentence type: requests or suggestions
Boomer style: nostalgic for the good old days
Target style: main character vibes

Boomer:
We used to spend all summer together as a family.

Generated Gen Alpha:
Back in the day, we were all vibing together the whole summer, like, as a unit.

Score: 4
Notes: The nostalgic statement about family time is rephrased to evoke a sense of shared experience and togetherness, fitting the 'main character vibes' by implying a cohesive group narrative.
====================================================================================================
ID: 12279
Topic: politics and news
Sentence type: requests or suggestions
Boomer style: overly polite to the point of awkward
Target style: low effort minimal energy

Boomer:
It would be wise to stay connected with the changes in governance.

Generated Gen Alpha:
Gotta keep up with what the government's doing.

Score: 5
Notes: Translates the advice to stay connected with governance changes into a very casual, low-effort suggestion.
====================================================================================================
ID: 16447
Topic: fashion and style
Sentence type: requests or suggestions
Boomer style: completely out of touch with youth culture
Target style: delulu and delusional optimism

Boomer:
You ought to choose practical bags for daily use.

Generated Gen Alpha:
You should def snag practical bags for everyday.

Score: 5
Notes: Rephrases the advice about practical bags with current informal language.
====================================================================================================
ID: 423
Topic: gaming and hobbies
Sentence type: warnings or advice
Boomer style: using outdated idioms
Target style: chronically online

Boomer:
Don't let your grades drop because of gaming.

Generated Gen Alpha:
Don't let gaming tank your grades.

Score: 5
Notes: Warning preserved, casual wording for grades dropping.

In [15]:
# =============================================================================
# 13. DISTRIBUTION CHECK
# =============================================================================
print("Final dataset rows:", len(translation_df))

print("\nTopic distribution:")
display(translation_df["topic"].value_counts())

print("\nSentence type distribution:")
display(translation_df["sentence_type"].value_counts())

print("\nScore distribution:")
display(translation_df["semantic_preservation_score"].value_counts())

print("\nTopic + sentence_type distribution:")
display(
    translation_df.groupby(["topic", "sentence_type"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
    .head(50)
)

Final dataset rows: 25000

Topic distribution:

topic
gaming and hobbies               2094
money and work                   1858
health and medicine              1810
weather and environment          1799
technology and social media      1758
family and home                  1755
food and cooking                 1724
relationships and dating         1644
politics and news                1591
fashion and style                1552
travel and going out             1531
school and studying              1481
pop culture and entertainment    1468
sports and fitness               1468
mental health and feelings       1467
Name: count, dtype: int64

Sentence type distribution:

sentence_type
compliments or praise         3504
complaints or frustrations    3246
requests or suggestions       3240
warnings or advice            3180
questions                     3119
commands or instructions      3016
exclamations or reactions     2849
observations or statements    2846
Name: count, dtype: int64

Score distribution:

semantic_preservation_score
5    19514
4     5486
Name: count, dtype: int64

Topic + sentence_type distribution:

                             topic               sentence_type  count
30              gaming and hobbies     requests or suggestions    389
31              gaming and hobbies          warnings or advice    373
53                  money and work                   questions    372
103    technology and social media          warnings or advice    363
34             health and medicine       compliments or praise    358
24              gaming and hobbies    commands or instructions    348
118        weather and environment     requests or suggestions    325
74        relationships and dating       compliments or praise    322
37             health and medicine                   questions    320
58               politics and news       compliments or praise    317
73        relationships and dating  complaints or frustrations    314
2                  family and home       compliments or praise    314
1                  family and home  complaints or frustrations    305
50                  money and work       compliments or praise    300
99     technology and social media   exclamations or reactions    297
16                food and cooking    commands or instructions    295
66   pop culture and entertainment       compliments or praise    290
77        relationships and dating                   questions    286
96     technology and social media    commands or instructions    285
87             school and studying          warnings or advice    285
115        weather and environment   exclamations or reactions    280
45      mental health and feelings                   questions    278
22                food and cooking     requests or suggestions    276
36             health and medicine  observations or statements    274
10               fashion and style       compliments or praise    268
20                food and cooking  observations or statements    267
113        weather and environment  complaints or frustrations    263
82             school and studying       compliments or praise    257
105           travel and going out  complaints or frustrations    249
49                  money and work  complaints or frustrations    248
93              sports and fitness                   questions    247
59               politics and news   exclamations or reactions    247
6                  family and home     requests or suggestions    245
19                food and cooking   exclamations or reactions    244
25              gaming and hobbies  complaints or frustrations    243
28              gaming and hobbies  observations or statements    241
104           travel and going out    commands or instructions    239
39             health and medicine          warnings or advice    238
65   pop culture and entertainment  complaints or frustrations    236
5                  family and home                   questions    232
55                  money and work          warnings or advice    228
116        weather and environment  observations or statements    227
56               politics and news    commands or instructions    226
62               politics and news     requests or suggestions    225
47      mental health and feelings          warnings or advice    224
109           travel and going out                   questions    223
107           travel and going out   exclamations or reactions    222
69   pop culture and entertainment                   questions    222
91              sports and fitness   exclamations or reactions    222
8                fashion and style    commands or instructions    221

## Notes

If you get `503 UNAVAILABLE`, do not delete the partial CSV. Wait a few minutes and rerun cell 9. The notebook will resume from the missing rows only.

Final dataset path:

```text
/Users/dzakyrizha/Downloads/NLP_GenAlpha_Dataset_Generation/output/generated_25000_gemini25_flashlite_prompt_final.csv
```